#!/usr/bin/env python3
"""Vendors libopus, opusfile and libopusenc into the directory containing this
script.

To update a library, bump its version in LIBS -- a release number, vendored
from its v-prefixed tag, or a full commit hash -- and run this script. It replaces
the three library subdirectories with fresh copies of the upstream releases,
reduced to the files the JUCE unity translation units need (the compiled .c
files and every header reachable from them), rewrites the sources' includes
for the JUCE include model (no -I directories), and writes a JUCE_UPSTREAM.txt
into each subdirectory, and generates the package_version.h that stands in
for upstream's package_version file. libogg is shared with the Ogg Vorbis
codec and lives in ../ogg. Needs git and Python 3.10+.
"""

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

LIBS = {
    "opus":       ("https://github.com/xiph/opus.git",       "1.6.1"),
    "opusfile":   ("https://github.com/xiph/opusfile.git",   "6dfd29e7adb87f2e193575fc3fa88cbf1a0b27df"),
    "libopusenc": ("https://github.com/xiph/libopusenc.git", "0.3"),
}

# The files each closure starts from: licences and the .c files the unity
# translation units compile. libopus's .c files come from its own source lists.
ROOTS = {
    "opus": ["COPYING", "LICENSE_PLEASE_READ.txt"],
    "opusfile": ["COPYING", "src/http.c", "src/info.c", "src/internal.c",
                 "src/opusfile.c", "src/stream.c"],
    "libopusenc": ["COPYING", "src/ogg_packer.c", "src/opus_header.c", "src/opusenc.c",
                   "src/picture.c", "src/resample.c", "src/unicode_support.c"],
}

OPUS_SOURCE_LISTS = {
    "opus_sources.mk": ["OPUS_SOURCES", "OPUS_SOURCES_FLOAT"],
    "celt_sources.mk": ["CELT_SOURCES", "CELT_SOURCES_SSE", "CELT_SOURCES_SSE2",
                        "CELT_SOURCES_ARM_NEON_INTR"],
    "silk_sources.mk": ["SILK_SOURCES", "SILK_SOURCES_FLOAT", "SILK_SOURCES_ARM_NEON_INTR"],
}

# Upstream's include search order per library, as (library, directory) pairs.
SEARCH_DIRS = {
    "opus": [("opus", "include"), ("opus", "celt"), ("opus", "silk"),
             ("opus", "silk/float"), ("opus", "src"), ("opus", ".")],
    "opusfile": [("opusfile", "include"), ("ogg", "include"), ("opus", "include")],
    "libopusenc": [("libopusenc", "include"), ("libopusenc", "src"), ("opus", "include")],
}

# Headers only reached through configurations that are never enabled here:
# fixed-point, MIPS, Xtensa, ARMv4/v5E, NE10, C5x/C6x, SSE4.1, the AArch64
# NEON macro set (upstream's CMake build does not set it either), HTTP.
EXCLUDE = re.compile(r"/fixed/|/mips/|/xtensa/|armv4|armv5e|ne10|c5x|c6x|fixed|"
                     r"fft_arm\.h|mdct_arm\.h|celt_lpc_sse\.h|main_sse\.h|SigProc_FIX_sse\.h|macros_arm64\.h|"
                     r"winerrno\.h")

INCLUDE_RE = re.compile(r'^(\s*#\s*include\s*)(["<])([^">]+)([">])', re.M)

# Libraries whose sources use PACKAGE_NAME / PACKAGE_VERSION.
PACKAGE_VERSION_HEADERS = ("opus", "libopusenc")

PACKAGE_VERSION_HEADER = """// Generated by vendor.py in place of upstream's package_version file.
#define PACKAGE_NAME "{name}"
#define PACKAGE_VERSION "{version}"
"""

UPSTREAM_NOTE = """Upstream: {repo}
Version:  {version} ({ref})

Vendored by vendor.py in the parent directory; rerun it to update. It copies
the .c files the unity translation units compile and every header reachable
from them, and rewrites their includes as paths relative to the including
file.
"""


# Interprets the provided path constituents relative to the location of this
# script, and returns an absolute Path to the resulting location.
#
# E.g. rel_to_py(".") returns an absolute path to the directory containing this
# script.
def rel_to_py(*paths) -> Path:
    return Path(
        os.path.realpath(
            os.path.join(os.path.realpath(os.path.dirname(__file__)), *paths)
        )
    )


def git(*args) -> str:
    return subprocess.run(
        ["git", *args], check=True, capture_output=True, text=True
    ).stdout.strip()


def is_commit(version: str) -> bool:
    return re.fullmatch(r"[0-9a-f]{40}", version) is not None


def clone(repo: str, version: str, dest: Path):
    if is_commit(version):
        git("clone", "--quiet", repo, str(dest))
        git("-C", str(dest), "checkout", "--quiet", version)
    else:
        git("clone", "--quiet", "--depth", "1", "--branch", f"v{version}", repo, str(dest))


def write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, newline="\n")


def sources_from_mk(opus: Path) -> list:
    sources = []
    for mk, variables in OPUS_SOURCE_LISTS.items():
        text = (opus / mk).read_text().replace("\\\n", " ")
        for variable in variables:
            sources += re.search(rf"^{variable}\s*=(.*)$", text, re.M).group(1).split()
    return sources


def resolve(lib: str, file: Path, name: str, trees: dict):
    candidates = [file.parent / name] + [trees[l] / d / name for l, d in SEARCH_DIRS[lib]]
    return next((c.resolve() for c in candidates if c.is_file()), None)


def closure(lib: str, roots: list, trees: dict) -> set:
    seen, todo = set(), [trees[lib] / r for r in roots]
    while todo:
        file = todo.pop()
        if file in seen:
            continue
        assert file.is_file(), file
        seen.add(file)
        if file.suffix not in (".c", ".h"):
            continue
        for match in INCLUDE_RE.finditer(file.read_text(errors="replace")):
            target = resolve(lib, file, match.group(3), trees)
            if (target is not None and target.is_relative_to(trees[lib])
                    and not EXCLUDE.search(target.relative_to(trees[lib]).as_posix())):
                todo.append(target)
    return seen


def rewrite_includes(lib: str, file: Path, trees: dict):
    def relative(match):
        name = match.group(3)
        if (file.parent / name).is_file():
            return match.group(0)
        target = resolve(lib, file, name, trees)
        if target is None:
            return match.group(0)
        return f'{match.group(1)}"{Path(os.path.relpath(target, file.parent)).as_posix()}"'

    write(file, INCLUDE_RE.sub(relative, file.read_text()))


def main():
    dest = rel_to_py(".")
    dest_trees = {lib: dest / lib for lib in LIBS} | {"ogg": rel_to_py("../ogg")}

    with tempfile.TemporaryDirectory() as tmp:
        trees = {lib: Path(tmp).resolve() / lib for lib in LIBS} | {"ogg": rel_to_py("../ogg")}
        for lib, (repo, version) in LIBS.items():
            clone(repo, version, trees[lib])
        roots = dict(ROOTS)
        roots["opus"] = roots["opus"] + sources_from_mk(trees["opus"])

        for lib, (repo, version) in LIBS.items():
            shutil.rmtree(dest / lib, ignore_errors=True)
            for file in closure(lib, roots[lib], trees):
                write(dest / lib / file.relative_to(trees[lib]), file.read_text())
            described = git("-C", str(trees[lib]), "describe", "--tags", "--match", "v*").removeprefix("v")
            commit = git("-C", str(trees[lib]), "rev-parse", "HEAD")
            ref = f"commit {commit}" if is_commit(version) else f"tag v{version}, commit {commit}"
            write(dest / lib / "JUCE_UPSTREAM.txt", UPSTREAM_NOTE.format(repo=repo, version=described, ref=ref))
            if lib in PACKAGE_VERSION_HEADERS:
                described = git("-C", str(trees[lib]), "describe", "--tags", "--match", "v*")
                write(dest / lib / "package_version.h",
                      PACKAGE_VERSION_HEADER.format(name=lib, version=described.removeprefix("v")))

    for lib in LIBS:
        for file in list((dest / lib).rglob("*.c")) + list((dest / lib).rglob("*.h")):
            rewrite_includes(lib, file, dest_trees)


if __name__ == "__main__":
    main()
