/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_BIDI_TYPE_LOOKUP_H
#define _SB_INTERNAL_BIDI_TYPE_LOOKUP_H

#include <juce_graphics/unicode/sheenbidi/Headers/SBBidiType.h>
#include <juce_graphics/unicode/sheenbidi/Headers/SBConfig.h>

#include "SBBase.h"

SB_INTERNAL SBBidiType LookupBidiType(SBCodepoint codepoint);

#endif
