/*
 * Automatically generated by SheenBidiGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H
#define _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H

#include <SheenBidi/SBBase.h>
#include <SheenBidi/SBCodepoint.h>
#include <SheenBidi/SBConfig.h>
#include <SheenBidi/SBGeneralCategory.h>

SB_INTERNAL SBGeneralCategory LookupGeneralCategory(SBCodepoint codepoint);

#endif
