/*
 * Automatically generated by SheenBidiGenerator tool. 
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H
#define _SB_INTERNAL_GENERAL_CATEGORY_LOOKUP_H

#include <SBConfig.h>
#include <SBGeneralCategory.h>

#include "SBBase.h"

SB_INTERNAL SBGeneralCategory LookupGeneralCategory(SBCodepoint codepoint);

#endif
