/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_SCRIPT_LOOKUP_H
#define _SB_INTERNAL_SCRIPT_LOOKUP_H

#include <SBConfig.h>
#include <SBScript.h>

#include "SBBase.h"

SB_INTERNAL SBScript LookupScript(SBCodepoint codepoint);

#endif
