/*
 * Automatically generated by SheenBidiGenerator tool.
 * DO NOT EDIT!!
 */

#ifndef _SB_INTERNAL_SCRIPT_LOOKUP_H
#define _SB_INTERNAL_SCRIPT_LOOKUP_H

#include <SheenBidi/SBBase.h>
#include <SheenBidi/SBCodepoint.h>
#include <SheenBidi/SBConfig.h>
#include <SheenBidi/SBScript.h>

SB_INTERNAL SBScript LookupScript(SBCodepoint codepoint);

#endif
