# Automatically generated makefile, created by the Introjucer
# Don't edit this file! Your changes will be overwritten when you re-save the Introjucer project!

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifeq ($(TARGET_ARCH_ABI), armeabi-v7a)
    LOCAL_ARM_MODE := arm
endif

LOCAL_MODULE := juce_jni
LOCAL_SRC_FILES := \
  ../../../Source/Main.cpp\
  ../../../Source/MainWindow.cpp\
  ../../../Source/MainWindow.h\
  ../../../Source/DemoUtilities.h\
  ../../../Source/IntroScreen.cpp\
  ../../../Source/JuceDemoHeader.h\
  ../../../Source/Demos/AnimationDemo.cpp\
  ../../../Source/Demos/AudioLatencyDemo.cpp\
  ../../../Source/Demos/AudioLiveScrollingDisplay.h\
  ../../../Source/Demos/AudioPlaybackDemo.cpp\
  ../../../Source/Demos/AudioRecordingDemo.cpp\
  ../../../Source/Demos/AudioSettingsDemo.cpp\
  ../../../Source/Demos/AudioSynthesiserDemo.cpp\
  ../../../Source/Demos/Box2DDemo.cpp\
  ../../../Source/Demos/CameraDemo.cpp\
  ../../../Source/Demos/ChildProcessDemo.cpp\
  ../../../Source/Demos/CodeEditorDemo.cpp\
  ../../../Source/Demos/ComponentTransformsDemo.cpp\
  ../../../Source/Demos/CryptographyDemo.cpp\
  ../../../Source/Demos/DialogsDemo.cpp\
  ../../../Source/Demos/FontsDemo.cpp\
  ../../../Source/Demos/GraphicsDemo.cpp\
  ../../../Source/Demos/ImagesDemo.cpp\
  ../../../Source/Demos/JavaScript.cpp\
  ../../../Source/Demos/KeyMappingsDemo.cpp\
  ../../../Source/Demos/LiveConstantDemo.cpp\
  ../../../Source/Demos/LookAndFeelDemo.cpp\
  ../../../Source/Demos/MDIDemo.cpp\
  ../../../Source/Demos/MidiDemo.cpp\
  ../../../Source/Demos/MultithreadingDemo.cpp\
  ../../../Source/Demos/MultiTouch.cpp\
  ../../../Source/Demos/NetworkingDemo.cpp\
  ../../../Source/Demos/OpenGLDemo.cpp\
  ../../../Source/Demos/OpenGLDemo2D.cpp\
  ../../../Source/Demos/PropertiesDemo.cpp\
  ../../../Source/Demos/SystemInfoDemo.cpp\
  ../../../Source/Demos/TimersAndEventsDemo.cpp\
  ../../../Source/Demos/UnitTestsDemo.cpp\
  ../../../Source/Demos/ValueTreesDemo.cpp\
  ../../../Source/Demos/VideoDemo.cpp\
  ../../../Source/Demos/WavefrontObjParser.h\
  ../../../Source/Demos/WebBrowserDemo.cpp\
  ../../../Source/Demos/WidgetsDemo.cpp\
  ../../../Source/Demos/WindowsDemo.cpp\
  ../../../Source/Demos/XMLandJSONDemo.cpp\
  ../../../Resources/tile_background.png\
  ../../../Resources/cello.wav\
  ../../../Resources/demo\ table\ data.xml\
  ../../../Resources/icons.zip\
  ../../../Resources/juce_icon.png\
  ../../../Resources/juce_module_info\
  ../../../Resources/portmeirion.jpg\
  ../../../Resources/teapot.obj\
  ../../../Resources/treedemo.xml\
  ../../../../../modules/juce_audio_basics/buffers/juce_AudioDataConverters.cpp\
  ../../../../../modules/juce_audio_basics/buffers/juce_AudioDataConverters.h\
  ../../../../../modules/juce_audio_basics/buffers/juce_AudioSampleBuffer.h\
  ../../../../../modules/juce_audio_basics/buffers/juce_FloatVectorOperations.cpp\
  ../../../../../modules/juce_audio_basics/buffers/juce_FloatVectorOperations.h\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiBuffer.cpp\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiBuffer.h\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiFile.cpp\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiFile.h\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiKeyboardState.cpp\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiKeyboardState.h\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiMessage.cpp\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiMessage.h\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiMessageSequence.cpp\
  ../../../../../modules/juce_audio_basics/midi/juce_MidiMessageSequence.h\
  ../../../../../modules/juce_audio_basics/effects/juce_Decibels.h\
  ../../../../../modules/juce_audio_basics/effects/juce_FFT.cpp\
  ../../../../../modules/juce_audio_basics/effects/juce_FFT.h\
  ../../../../../modules/juce_audio_basics/effects/juce_IIRFilter.cpp\
  ../../../../../modules/juce_audio_basics/effects/juce_IIRFilter.h\
  ../../../../../modules/juce_audio_basics/effects/juce_LagrangeInterpolator.cpp\
  ../../../../../modules/juce_audio_basics/effects/juce_LagrangeInterpolator.h\
  ../../../../../modules/juce_audio_basics/effects/juce_Reverb.h\
  ../../../../../modules/juce_audio_basics/sources/juce_AudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_BufferingAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_BufferingAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_ChannelRemappingAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_ChannelRemappingAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_IIRFilterAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_IIRFilterAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_MixerAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_MixerAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_PositionableAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_ResamplingAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_ResamplingAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_ReverbAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_ReverbAudioSource.h\
  ../../../../../modules/juce_audio_basics/sources/juce_ToneGeneratorAudioSource.cpp\
  ../../../../../modules/juce_audio_basics/sources/juce_ToneGeneratorAudioSource.h\
  ../../../../../modules/juce_audio_basics/synthesisers/juce_Synthesiser.cpp\
  ../../../../../modules/juce_audio_basics/synthesisers/juce_Synthesiser.h\
  ../../../../../modules/juce_audio_basics/juce_module_info\
  ../../../../../modules/juce_audio_basics/juce_audio_basics.h\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.h\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioIODevice.cpp\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioIODevice.h\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioIODeviceType.cpp\
  ../../../../../modules/juce_audio_devices/audio_io/juce_AudioIODeviceType.h\
  ../../../../../modules/juce_audio_devices/audio_io/juce_SystemAudioVolume.h\
  ../../../../../modules/juce_audio_devices/midi_io/juce_MidiInput.h\
  ../../../../../modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.cpp\
  ../../../../../modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.h\
  ../../../../../modules/juce_audio_devices/midi_io/juce_MidiOutput.cpp\
  ../../../../../modules/juce_audio_devices/midi_io/juce_MidiOutput.h\
  ../../../../../modules/juce_audio_devices/sources/juce_AudioSourcePlayer.cpp\
  ../../../../../modules/juce_audio_devices/sources/juce_AudioSourcePlayer.h\
  ../../../../../modules/juce_audio_devices/sources/juce_AudioTransportSource.cpp\
  ../../../../../modules/juce_audio_devices/sources/juce_AudioTransportSource.h\
  ../../../../../modules/juce_audio_devices/audio_cd/juce_AudioCDBurner.h\
  ../../../../../modules/juce_audio_devices/audio_cd/juce_AudioCDReader.cpp\
  ../../../../../modules/juce_audio_devices/audio_cd/juce_AudioCDReader.h\
  ../../../../../modules/juce_audio_devices/native/juce_android_Audio.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_android_Midi.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_android_OpenSL.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_ios_Audio.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_linux_ALSA.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_linux_AudioCDReader.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_linux_JackAudio.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_linux_Midi.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_mac_AudioCDBurner.mm\
  ../../../../../modules/juce_audio_devices/native/juce_mac_AudioCDReader.mm\
  ../../../../../modules/juce_audio_devices/native/juce_mac_CoreAudio.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_mac_CoreMidi.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_MidiDataConcatenator.h\
  ../../../../../modules/juce_audio_devices/native/juce_win32_ASIO.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_win32_AudioCDBurner.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_win32_AudioCDReader.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_win32_DirectSound.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_win32_Midi.cpp\
  ../../../../../modules/juce_audio_devices/native/juce_win32_WASAPI.cpp\
  ../../../../../modules/juce_audio_devices/juce_module_info\
  ../../../../../modules/juce_audio_devices/juce_audio_devices.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormat.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatManager.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatManager.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatReader.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatReader.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatReaderSource.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatReaderSource.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatWriter.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioFormatWriter.h\
  ../../../../../modules/juce_audio_formats/format/juce_AudioSubsectionReader.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_AudioSubsectionReader.h\
  ../../../../../modules/juce_audio_formats/format/juce_BufferingAudioFormatReader.cpp\
  ../../../../../modules/juce_audio_formats/format/juce_BufferingAudioFormatReader.h\
  ../../../../../modules/juce_audio_formats/format/juce_MemoryMappedAudioFormatReader.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_AiffAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_AiffAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_CoreAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_CoreAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_FlacAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_FlacAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_LAMEEncoderAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_LAMEEncoderAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_MP3AudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_MP3AudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_OggVorbisAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_OggVorbisAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_QuickTimeAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_QuickTimeAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_WavAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_WavAudioFormat.h\
  ../../../../../modules/juce_audio_formats/codecs/juce_WindowsMediaAudioFormat.cpp\
  ../../../../../modules/juce_audio_formats/codecs/juce_WindowsMediaAudioFormat.h\
  ../../../../../modules/juce_audio_formats/sampler/juce_Sampler.cpp\
  ../../../../../modules/juce_audio_formats/sampler/juce_Sampler.h\
  ../../../../../modules/juce_audio_formats/juce_module_info\
  ../../../../../modules/juce_audio_formats/juce_audio_formats.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioPlayHead.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioPluginInstance.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessor.cpp\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessor.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorEditor.cpp\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorEditor.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorGraph.cpp\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorGraph.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorListener.h\
  ../../../../../modules/juce_audio_processors/processors/juce_AudioProcessorParameter.h\
  ../../../../../modules/juce_audio_processors/processors/juce_GenericAudioProcessorEditor.cpp\
  ../../../../../modules/juce_audio_processors/processors/juce_GenericAudioProcessorEditor.h\
  ../../../../../modules/juce_audio_processors/processors/juce_PluginDescription.cpp\
  ../../../../../modules/juce_audio_processors/processors/juce_PluginDescription.h\
  ../../../../../modules/juce_audio_processors/format/juce_AudioPluginFormat.cpp\
  ../../../../../modules/juce_audio_processors/format/juce_AudioPluginFormat.h\
  ../../../../../modules/juce_audio_processors/format/juce_AudioPluginFormatManager.cpp\
  ../../../../../modules/juce_audio_processors/format/juce_AudioPluginFormatManager.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_AudioUnitPluginFormat.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_AudioUnitPluginFormat.mm\
  ../../../../../modules/juce_audio_processors/format_types/juce_LADSPAPluginFormat.cpp\
  ../../../../../modules/juce_audio_processors/format_types/juce_LADSPAPluginFormat.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_VST3Common.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_VST3Headers.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_VST3PluginFormat.cpp\
  ../../../../../modules/juce_audio_processors/format_types/juce_VST3PluginFormat.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_VSTMidiEventList.h\
  ../../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp\
  ../../../../../modules/juce_audio_processors/format_types/juce_VSTPluginFormat.h\
  ../../../../../modules/juce_audio_processors/scanning/juce_KnownPluginList.cpp\
  ../../../../../modules/juce_audio_processors/scanning/juce_KnownPluginList.h\
  ../../../../../modules/juce_audio_processors/scanning/juce_PluginDirectoryScanner.cpp\
  ../../../../../modules/juce_audio_processors/scanning/juce_PluginDirectoryScanner.h\
  ../../../../../modules/juce_audio_processors/scanning/juce_PluginListComponent.cpp\
  ../../../../../modules/juce_audio_processors/scanning/juce_PluginListComponent.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioParameterBool.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioParameterChoice.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioParameterFloat.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioParameterInt.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioProcessorParameters.cpp\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioProcessorParameterWithID.h\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioProcessorValueTreeState.cpp\
  ../../../../../modules/juce_audio_processors/utilities/juce_AudioProcessorValueTreeState.h\
  ../../../../../modules/juce_audio_processors/juce_module_info\
  ../../../../../modules/juce_audio_processors/juce_audio_processors.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioAppComponent.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioAppComponent.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioDeviceSelectorComponent.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioDeviceSelectorComponent.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioThumbnail.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioThumbnail.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioThumbnailBase.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioThumbnailCache.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioThumbnailCache.h\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioVisualiserComponent.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_AudioVisualiserComponent.h\
  ../../../../../modules/juce_audio_utils/gui/juce_MidiKeyboardComponent.cpp\
  ../../../../../modules/juce_audio_utils/gui/juce_MidiKeyboardComponent.h\
  ../../../../../modules/juce_audio_utils/players/juce_AudioProcessorPlayer.cpp\
  ../../../../../modules/juce_audio_utils/players/juce_AudioProcessorPlayer.h\
  ../../../../../modules/juce_audio_utils/juce_module_info\
  ../../../../../modules/juce_audio_utils/juce_audio_utils.h\
  ../../../../../modules/juce_box2d/box2d/Box2D.h\
  ../../../../../modules/juce_box2d/box2d/README.txt\
  ../../../../../modules/juce_box2d/utils/juce_Box2DRenderer.cpp\
  ../../../../../modules/juce_box2d/utils/juce_Box2DRenderer.h\
  ../../../../../modules/juce_box2d/juce_module_info\
  ../../../../../modules/juce_box2d/juce_box2d.h\
  ../../../../../modules/juce_core/text/juce_Base64.cpp\
  ../../../../../modules/juce_core/text/juce_Base64.h\
  ../../../../../modules/juce_core/text/juce_CharacterFunctions.cpp\
  ../../../../../modules/juce_core/text/juce_CharacterFunctions.h\
  ../../../../../modules/juce_core/text/juce_CharPointer_ASCII.h\
  ../../../../../modules/juce_core/text/juce_CharPointer_UTF8.h\
  ../../../../../modules/juce_core/text/juce_CharPointer_UTF16.h\
  ../../../../../modules/juce_core/text/juce_CharPointer_UTF32.h\
  ../../../../../modules/juce_core/text/juce_Identifier.cpp\
  ../../../../../modules/juce_core/text/juce_Identifier.h\
  ../../../../../modules/juce_core/text/juce_LocalisedStrings.cpp\
  ../../../../../modules/juce_core/text/juce_LocalisedStrings.h\
  ../../../../../modules/juce_core/text/juce_NewLine.h\
  ../../../../../modules/juce_core/text/juce_String.cpp\
  ../../../../../modules/juce_core/text/juce_String.h\
  ../../../../../modules/juce_core/text/juce_StringArray.cpp\
  ../../../../../modules/juce_core/text/juce_StringArray.h\
  ../../../../../modules/juce_core/text/juce_StringPairArray.cpp\
  ../../../../../modules/juce_core/text/juce_StringPairArray.h\
  ../../../../../modules/juce_core/text/juce_StringPool.cpp\
  ../../../../../modules/juce_core/text/juce_StringPool.h\
  ../../../../../modules/juce_core/text/juce_StringRef.h\
  ../../../../../modules/juce_core/text/juce_TextDiff.cpp\
  ../../../../../modules/juce_core/text/juce_TextDiff.h\
  ../../../../../modules/juce_core/maths/juce_BigInteger.cpp\
  ../../../../../modules/juce_core/maths/juce_BigInteger.h\
  ../../../../../modules/juce_core/maths/juce_Expression.cpp\
  ../../../../../modules/juce_core/maths/juce_Expression.h\
  ../../../../../modules/juce_core/maths/juce_MathsFunctions.h\
  ../../../../../modules/juce_core/maths/juce_NormalisableRange.h\
  ../../../../../modules/juce_core/maths/juce_Random.cpp\
  ../../../../../modules/juce_core/maths/juce_Random.h\
  ../../../../../modules/juce_core/maths/juce_Range.h\
  ../../../../../modules/juce_core/memory/juce_Atomic.h\
  ../../../../../modules/juce_core/memory/juce_ByteOrder.h\
  ../../../../../modules/juce_core/memory/juce_ContainerDeletePolicy.h\
  ../../../../../modules/juce_core/memory/juce_HeapBlock.h\
  ../../../../../modules/juce_core/memory/juce_LeakedObjectDetector.h\
  ../../../../../modules/juce_core/memory/juce_Memory.h\
  ../../../../../modules/juce_core/memory/juce_MemoryBlock.cpp\
  ../../../../../modules/juce_core/memory/juce_MemoryBlock.h\
  ../../../../../modules/juce_core/memory/juce_OptionalScopedPointer.h\
  ../../../../../modules/juce_core/memory/juce_ReferenceCountedObject.h\
  ../../../../../modules/juce_core/memory/juce_ScopedPointer.h\
  ../../../../../modules/juce_core/memory/juce_SharedResourcePointer.h\
  ../../../../../modules/juce_core/memory/juce_Singleton.h\
  ../../../../../modules/juce_core/memory/juce_WeakReference.h\
  ../../../../../modules/juce_core/containers/juce_AbstractFifo.cpp\
  ../../../../../modules/juce_core/containers/juce_AbstractFifo.h\
  ../../../../../modules/juce_core/containers/juce_Array.h\
  ../../../../../modules/juce_core/containers/juce_ArrayAllocationBase.h\
  ../../../../../modules/juce_core/containers/juce_DynamicObject.cpp\
  ../../../../../modules/juce_core/containers/juce_DynamicObject.h\
  ../../../../../modules/juce_core/containers/juce_ElementComparator.h\
  ../../../../../modules/juce_core/containers/juce_HashMap.h\
  ../../../../../modules/juce_core/containers/juce_LinkedListPointer.h\
  ../../../../../modules/juce_core/containers/juce_NamedValueSet.cpp\
  ../../../../../modules/juce_core/containers/juce_NamedValueSet.h\
  ../../../../../modules/juce_core/containers/juce_OwnedArray.h\
  ../../../../../modules/juce_core/containers/juce_PropertySet.cpp\
  ../../../../../modules/juce_core/containers/juce_PropertySet.h\
  ../../../../../modules/juce_core/containers/juce_ReferenceCountedArray.h\
  ../../../../../modules/juce_core/containers/juce_ScopedValueSetter.h\
  ../../../../../modules/juce_core/containers/juce_SortedSet.h\
  ../../../../../modules/juce_core/containers/juce_SparseSet.h\
  ../../../../../modules/juce_core/containers/juce_Variant.cpp\
  ../../../../../modules/juce_core/containers/juce_Variant.h\
  ../../../../../modules/juce_core/threads/juce_ChildProcess.cpp\
  ../../../../../modules/juce_core/threads/juce_ChildProcess.h\
  ../../../../../modules/juce_core/threads/juce_CriticalSection.h\
  ../../../../../modules/juce_core/threads/juce_DynamicLibrary.h\
  ../../../../../modules/juce_core/threads/juce_HighResolutionTimer.cpp\
  ../../../../../modules/juce_core/threads/juce_HighResolutionTimer.h\
  ../../../../../modules/juce_core/threads/juce_InterProcessLock.h\
  ../../../../../modules/juce_core/threads/juce_Process.h\
  ../../../../../modules/juce_core/threads/juce_ReadWriteLock.cpp\
  ../../../../../modules/juce_core/threads/juce_ReadWriteLock.h\
  ../../../../../modules/juce_core/threads/juce_ScopedLock.h\
  ../../../../../modules/juce_core/threads/juce_ScopedReadLock.h\
  ../../../../../modules/juce_core/threads/juce_ScopedWriteLock.h\
  ../../../../../modules/juce_core/threads/juce_SpinLock.h\
  ../../../../../modules/juce_core/threads/juce_Thread.cpp\
  ../../../../../modules/juce_core/threads/juce_Thread.h\
  ../../../../../modules/juce_core/threads/juce_ThreadLocalValue.h\
  ../../../../../modules/juce_core/threads/juce_ThreadPool.cpp\
  ../../../../../modules/juce_core/threads/juce_ThreadPool.h\
  ../../../../../modules/juce_core/threads/juce_TimeSliceThread.cpp\
  ../../../../../modules/juce_core/threads/juce_TimeSliceThread.h\
  ../../../../../modules/juce_core/threads/juce_WaitableEvent.h\
  ../../../../../modules/juce_core/time/juce_PerformanceCounter.cpp\
  ../../../../../modules/juce_core/time/juce_PerformanceCounter.h\
  ../../../../../modules/juce_core/time/juce_RelativeTime.cpp\
  ../../../../../modules/juce_core/time/juce_RelativeTime.h\
  ../../../../../modules/juce_core/time/juce_Time.cpp\
  ../../../../../modules/juce_core/time/juce_Time.h\
  ../../../../../modules/juce_core/files/juce_DirectoryIterator.cpp\
  ../../../../../modules/juce_core/files/juce_DirectoryIterator.h\
  ../../../../../modules/juce_core/files/juce_File.cpp\
  ../../../../../modules/juce_core/files/juce_File.h\
  ../../../../../modules/juce_core/files/juce_FileFilter.cpp\
  ../../../../../modules/juce_core/files/juce_FileFilter.h\
  ../../../../../modules/juce_core/files/juce_FileInputStream.cpp\
  ../../../../../modules/juce_core/files/juce_FileInputStream.h\
  ../../../../../modules/juce_core/files/juce_FileOutputStream.cpp\
  ../../../../../modules/juce_core/files/juce_FileOutputStream.h\
  ../../../../../modules/juce_core/files/juce_FileSearchPath.cpp\
  ../../../../../modules/juce_core/files/juce_FileSearchPath.h\
  ../../../../../modules/juce_core/files/juce_MemoryMappedFile.h\
  ../../../../../modules/juce_core/files/juce_TemporaryFile.cpp\
  ../../../../../modules/juce_core/files/juce_TemporaryFile.h\
  ../../../../../modules/juce_core/files/juce_WildcardFileFilter.cpp\
  ../../../../../modules/juce_core/files/juce_WildcardFileFilter.h\
  ../../../../../modules/juce_core/network/juce_IPAddress.cpp\
  ../../../../../modules/juce_core/network/juce_IPAddress.h\
  ../../../../../modules/juce_core/network/juce_MACAddress.cpp\
  ../../../../../modules/juce_core/network/juce_MACAddress.h\
  ../../../../../modules/juce_core/network/juce_NamedPipe.cpp\
  ../../../../../modules/juce_core/network/juce_NamedPipe.h\
  ../../../../../modules/juce_core/network/juce_Socket.cpp\
  ../../../../../modules/juce_core/network/juce_Socket.h\
  ../../../../../modules/juce_core/network/juce_URL.cpp\
  ../../../../../modules/juce_core/network/juce_URL.h\
  ../../../../../modules/juce_core/streams/juce_BufferedInputStream.cpp\
  ../../../../../modules/juce_core/streams/juce_BufferedInputStream.h\
  ../../../../../modules/juce_core/streams/juce_FileInputSource.cpp\
  ../../../../../modules/juce_core/streams/juce_FileInputSource.h\
  ../../../../../modules/juce_core/streams/juce_InputSource.h\
  ../../../../../modules/juce_core/streams/juce_InputStream.cpp\
  ../../../../../modules/juce_core/streams/juce_InputStream.h\
  ../../../../../modules/juce_core/streams/juce_MemoryInputStream.cpp\
  ../../../../../modules/juce_core/streams/juce_MemoryInputStream.h\
  ../../../../../modules/juce_core/streams/juce_MemoryOutputStream.cpp\
  ../../../../../modules/juce_core/streams/juce_MemoryOutputStream.h\
  ../../../../../modules/juce_core/streams/juce_OutputStream.cpp\
  ../../../../../modules/juce_core/streams/juce_OutputStream.h\
  ../../../../../modules/juce_core/streams/juce_SubregionStream.cpp\
  ../../../../../modules/juce_core/streams/juce_SubregionStream.h\
  ../../../../../modules/juce_core/logging/juce_FileLogger.cpp\
  ../../../../../modules/juce_core/logging/juce_FileLogger.h\
  ../../../../../modules/juce_core/logging/juce_Logger.cpp\
  ../../../../../modules/juce_core/logging/juce_Logger.h\
  ../../../../../modules/juce_core/system/juce_CompilerSupport.h\
  ../../../../../modules/juce_core/system/juce_PlatformDefs.h\
  ../../../../../modules/juce_core/system/juce_StandardHeader.h\
  ../../../../../modules/juce_core/system/juce_SystemStats.cpp\
  ../../../../../modules/juce_core/system/juce_SystemStats.h\
  ../../../../../modules/juce_core/system/juce_TargetPlatform.h\
  ../../../../../modules/juce_core/xml/juce_XmlDocument.cpp\
  ../../../../../modules/juce_core/xml/juce_XmlDocument.h\
  ../../../../../modules/juce_core/xml/juce_XmlElement.cpp\
  ../../../../../modules/juce_core/xml/juce_XmlElement.h\
  ../../../../../modules/juce_core/javascript/juce_Javascript.cpp\
  ../../../../../modules/juce_core/javascript/juce_Javascript.h\
  ../../../../../modules/juce_core/javascript/juce_JSON.cpp\
  ../../../../../modules/juce_core/javascript/juce_JSON.h\
  ../../../../../modules/juce_core/zip/juce_GZIPCompressorOutputStream.cpp\
  ../../../../../modules/juce_core/zip/juce_GZIPCompressorOutputStream.h\
  ../../../../../modules/juce_core/zip/juce_GZIPDecompressorInputStream.cpp\
  ../../../../../modules/juce_core/zip/juce_GZIPDecompressorInputStream.h\
  ../../../../../modules/juce_core/zip/juce_ZipFile.cpp\
  ../../../../../modules/juce_core/zip/juce_ZipFile.h\
  ../../../../../modules/juce_core/unit_tests/juce_UnitTest.cpp\
  ../../../../../modules/juce_core/unit_tests/juce_UnitTest.h\
  ../../../../../modules/juce_core/misc/juce_Result.cpp\
  ../../../../../modules/juce_core/misc/juce_Result.h\
  ../../../../../modules/juce_core/misc/juce_Uuid.cpp\
  ../../../../../modules/juce_core/misc/juce_Uuid.h\
  ../../../../../modules/juce_core/misc/juce_WindowsRegistry.h\
  ../../../../../modules/juce_core/native/juce_android_Files.cpp\
  ../../../../../modules/juce_core/native/juce_android_JNIHelpers.h\
  ../../../../../modules/juce_core/native/juce_android_Misc.cpp\
  ../../../../../modules/juce_core/native/juce_android_Network.cpp\
  ../../../../../modules/juce_core/native/juce_android_SystemStats.cpp\
  ../../../../../modules/juce_core/native/juce_android_Threads.cpp\
  ../../../../../modules/juce_core/native/juce_BasicNativeHeaders.h\
  ../../../../../modules/juce_core/native/juce_curl_Network.cpp\
  ../../../../../modules/juce_core/native/juce_linux_CommonFile.cpp\
  ../../../../../modules/juce_core/native/juce_linux_Files.cpp\
  ../../../../../modules/juce_core/native/juce_linux_Network.cpp\
  ../../../../../modules/juce_core/native/juce_linux_SystemStats.cpp\
  ../../../../../modules/juce_core/native/juce_linux_Threads.cpp\
  ../../../../../modules/juce_core/native/juce_mac_Files.mm\
  ../../../../../modules/juce_core/native/juce_mac_Network.mm\
  ../../../../../modules/juce_core/native/juce_mac_Strings.mm\
  ../../../../../modules/juce_core/native/juce_mac_SystemStats.mm\
  ../../../../../modules/juce_core/native/juce_mac_Threads.mm\
  ../../../../../modules/juce_core/native/juce_osx_ObjCHelpers.h\
  ../../../../../modules/juce_core/native/juce_posix_NamedPipe.cpp\
  ../../../../../modules/juce_core/native/juce_posix_SharedCode.h\
  ../../../../../modules/juce_core/native/juce_win32_ComSmartPtr.h\
  ../../../../../modules/juce_core/native/juce_win32_Files.cpp\
  ../../../../../modules/juce_core/native/juce_win32_Network.cpp\
  ../../../../../modules/juce_core/native/juce_win32_Registry.cpp\
  ../../../../../modules/juce_core/native/juce_win32_SystemStats.cpp\
  ../../../../../modules/juce_core/native/juce_win32_Threads.cpp\
  ../../../../../modules/juce_core/juce_module_info\
  ../../../../../modules/juce_core/juce_core.h\
  ../../../../../modules/juce_cryptography/encryption/juce_BlowFish.cpp\
  ../../../../../modules/juce_cryptography/encryption/juce_BlowFish.h\
  ../../../../../modules/juce_cryptography/encryption/juce_Primes.cpp\
  ../../../../../modules/juce_cryptography/encryption/juce_Primes.h\
  ../../../../../modules/juce_cryptography/encryption/juce_RSAKey.cpp\
  ../../../../../modules/juce_cryptography/encryption/juce_RSAKey.h\
  ../../../../../modules/juce_cryptography/hashing/juce_MD5.cpp\
  ../../../../../modules/juce_cryptography/hashing/juce_MD5.h\
  ../../../../../modules/juce_cryptography/hashing/juce_SHA256.cpp\
  ../../../../../modules/juce_cryptography/hashing/juce_SHA256.h\
  ../../../../../modules/juce_cryptography/hashing/juce_Whirlpool.cpp\
  ../../../../../modules/juce_cryptography/hashing/juce_Whirlpool.h\
  ../../../../../modules/juce_cryptography/juce_module_info\
  ../../../../../modules/juce_cryptography/juce_cryptography.h\
  ../../../../../modules/juce_data_structures/values/juce_Value.cpp\
  ../../../../../modules/juce_data_structures/values/juce_Value.h\
  ../../../../../modules/juce_data_structures/values/juce_ValueTree.cpp\
  ../../../../../modules/juce_data_structures/values/juce_ValueTree.h\
  ../../../../../modules/juce_data_structures/values/juce_ValueTreeSynchroniser.cpp\
  ../../../../../modules/juce_data_structures/values/juce_ValueTreeSynchroniser.h\
  ../../../../../modules/juce_data_structures/undomanager/juce_UndoableAction.h\
  ../../../../../modules/juce_data_structures/undomanager/juce_UndoManager.cpp\
  ../../../../../modules/juce_data_structures/undomanager/juce_UndoManager.h\
  ../../../../../modules/juce_data_structures/app_properties/juce_ApplicationProperties.cpp\
  ../../../../../modules/juce_data_structures/app_properties/juce_ApplicationProperties.h\
  ../../../../../modules/juce_data_structures/app_properties/juce_PropertiesFile.cpp\
  ../../../../../modules/juce_data_structures/app_properties/juce_PropertiesFile.h\
  ../../../../../modules/juce_data_structures/juce_module_info\
  ../../../../../modules/juce_data_structures/juce_data_structures.h\
  ../../../../../modules/juce_events/messages/juce_ApplicationBase.cpp\
  ../../../../../modules/juce_events/messages/juce_ApplicationBase.h\
  ../../../../../modules/juce_events/messages/juce_CallbackMessage.h\
  ../../../../../modules/juce_events/messages/juce_DeletedAtShutdown.cpp\
  ../../../../../modules/juce_events/messages/juce_DeletedAtShutdown.h\
  ../../../../../modules/juce_events/messages/juce_Initialisation.h\
  ../../../../../modules/juce_events/messages/juce_Message.h\
  ../../../../../modules/juce_events/messages/juce_MessageListener.cpp\
  ../../../../../modules/juce_events/messages/juce_MessageListener.h\
  ../../../../../modules/juce_events/messages/juce_MessageManager.cpp\
  ../../../../../modules/juce_events/messages/juce_MessageManager.h\
  ../../../../../modules/juce_events/messages/juce_MountedVolumeListChangeDetector.h\
  ../../../../../modules/juce_events/messages/juce_NotificationType.h\
  ../../../../../modules/juce_events/timers/juce_MultiTimer.cpp\
  ../../../../../modules/juce_events/timers/juce_MultiTimer.h\
  ../../../../../modules/juce_events/timers/juce_Timer.cpp\
  ../../../../../modules/juce_events/timers/juce_Timer.h\
  ../../../../../modules/juce_events/broadcasters/juce_ActionBroadcaster.cpp\
  ../../../../../modules/juce_events/broadcasters/juce_ActionBroadcaster.h\
  ../../../../../modules/juce_events/broadcasters/juce_ActionListener.h\
  ../../../../../modules/juce_events/broadcasters/juce_AsyncUpdater.cpp\
  ../../../../../modules/juce_events/broadcasters/juce_AsyncUpdater.h\
  ../../../../../modules/juce_events/broadcasters/juce_ChangeBroadcaster.cpp\
  ../../../../../modules/juce_events/broadcasters/juce_ChangeBroadcaster.h\
  ../../../../../modules/juce_events/broadcasters/juce_ChangeListener.h\
  ../../../../../modules/juce_events/broadcasters/juce_ListenerList.h\
  ../../../../../modules/juce_events/interprocess/juce_ConnectedChildProcess.cpp\
  ../../../../../modules/juce_events/interprocess/juce_ConnectedChildProcess.h\
  ../../../../../modules/juce_events/interprocess/juce_InterprocessConnection.cpp\
  ../../../../../modules/juce_events/interprocess/juce_InterprocessConnection.h\
  ../../../../../modules/juce_events/interprocess/juce_InterprocessConnectionServer.cpp\
  ../../../../../modules/juce_events/interprocess/juce_InterprocessConnectionServer.h\
  ../../../../../modules/juce_events/native/juce_android_Messaging.cpp\
  ../../../../../modules/juce_events/native/juce_ios_MessageManager.mm\
  ../../../../../modules/juce_events/native/juce_linux_Messaging.cpp\
  ../../../../../modules/juce_events/native/juce_mac_MessageManager.mm\
  ../../../../../modules/juce_events/native/juce_osx_MessageQueue.h\
  ../../../../../modules/juce_events/native/juce_ScopedXLock.h\
  ../../../../../modules/juce_events/native/juce_win32_HiddenMessageWindow.h\
  ../../../../../modules/juce_events/native/juce_win32_Messaging.cpp\
  ../../../../../modules/juce_events/juce_module_info\
  ../../../../../modules/juce_events/juce_events.h\
  ../../../../../modules/juce_graphics/colour/juce_Colour.cpp\
  ../../../../../modules/juce_graphics/colour/juce_Colour.h\
  ../../../../../modules/juce_graphics/colour/juce_ColourGradient.cpp\
  ../../../../../modules/juce_graphics/colour/juce_ColourGradient.h\
  ../../../../../modules/juce_graphics/colour/juce_Colours.cpp\
  ../../../../../modules/juce_graphics/colour/juce_Colours.h\
  ../../../../../modules/juce_graphics/colour/juce_FillType.cpp\
  ../../../../../modules/juce_graphics/colour/juce_FillType.h\
  ../../../../../modules/juce_graphics/colour/juce_PixelFormats.h\
  ../../../../../modules/juce_graphics/contexts/juce_GraphicsContext.cpp\
  ../../../../../modules/juce_graphics/contexts/juce_GraphicsContext.h\
  ../../../../../modules/juce_graphics/contexts/juce_LowLevelGraphicsContext.h\
  ../../../../../modules/juce_graphics/contexts/juce_LowLevelGraphicsPostScriptRenderer.cpp\
  ../../../../../modules/juce_graphics/contexts/juce_LowLevelGraphicsPostScriptRenderer.h\
  ../../../../../modules/juce_graphics/contexts/juce_LowLevelGraphicsSoftwareRenderer.cpp\
  ../../../../../modules/juce_graphics/contexts/juce_LowLevelGraphicsSoftwareRenderer.h\
  ../../../../../modules/juce_graphics/images/juce_Image.cpp\
  ../../../../../modules/juce_graphics/images/juce_Image.h\
  ../../../../../modules/juce_graphics/images/juce_ImageCache.cpp\
  ../../../../../modules/juce_graphics/images/juce_ImageCache.h\
  ../../../../../modules/juce_graphics/images/juce_ImageConvolutionKernel.cpp\
  ../../../../../modules/juce_graphics/images/juce_ImageConvolutionKernel.h\
  ../../../../../modules/juce_graphics/images/juce_ImageFileFormat.cpp\
  ../../../../../modules/juce_graphics/images/juce_ImageFileFormat.h\
  ../../../../../modules/juce_graphics/image_formats/juce_GIFLoader.cpp\
  ../../../../../modules/juce_graphics/image_formats/juce_JPEGLoader.cpp\
  ../../../../../modules/juce_graphics/image_formats/juce_PNGLoader.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_AffineTransform.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_AffineTransform.h\
  ../../../../../modules/juce_graphics/geometry/juce_BorderSize.h\
  ../../../../../modules/juce_graphics/geometry/juce_EdgeTable.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_EdgeTable.h\
  ../../../../../modules/juce_graphics/geometry/juce_Line.h\
  ../../../../../modules/juce_graphics/geometry/juce_Path.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_Path.h\
  ../../../../../modules/juce_graphics/geometry/juce_PathIterator.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_PathIterator.h\
  ../../../../../modules/juce_graphics/geometry/juce_PathStrokeType.cpp\
  ../../../../../modules/juce_graphics/geometry/juce_PathStrokeType.h\
  ../../../../../modules/juce_graphics/geometry/juce_Point.h\
  ../../../../../modules/juce_graphics/geometry/juce_Rectangle.h\
  ../../../../../modules/juce_graphics/geometry/juce_RectangleList.h\
  ../../../../../modules/juce_graphics/placement/juce_Justification.h\
  ../../../../../modules/juce_graphics/placement/juce_RectanglePlacement.cpp\
  ../../../../../modules/juce_graphics/placement/juce_RectanglePlacement.h\
  ../../../../../modules/juce_graphics/fonts/juce_AttributedString.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_AttributedString.h\
  ../../../../../modules/juce_graphics/fonts/juce_CustomTypeface.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_CustomTypeface.h\
  ../../../../../modules/juce_graphics/fonts/juce_Font.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_Font.h\
  ../../../../../modules/juce_graphics/fonts/juce_GlyphArrangement.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_GlyphArrangement.h\
  ../../../../../modules/juce_graphics/fonts/juce_TextLayout.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_TextLayout.h\
  ../../../../../modules/juce_graphics/fonts/juce_Typeface.cpp\
  ../../../../../modules/juce_graphics/fonts/juce_Typeface.h\
  ../../../../../modules/juce_graphics/effects/juce_DropShadowEffect.cpp\
  ../../../../../modules/juce_graphics/effects/juce_DropShadowEffect.h\
  ../../../../../modules/juce_graphics/effects/juce_GlowEffect.cpp\
  ../../../../../modules/juce_graphics/effects/juce_GlowEffect.h\
  ../../../../../modules/juce_graphics/effects/juce_ImageEffectFilter.h\
  ../../../../../modules/juce_graphics/native/juce_android_Fonts.cpp\
  ../../../../../modules/juce_graphics/native/juce_android_GraphicsContext.cpp\
  ../../../../../modules/juce_graphics/native/juce_freetype_Fonts.cpp\
  ../../../../../modules/juce_graphics/native/juce_linux_Fonts.cpp\
  ../../../../../modules/juce_graphics/native/juce_mac_CoreGraphicsContext.h\
  ../../../../../modules/juce_graphics/native/juce_mac_CoreGraphicsContext.mm\
  ../../../../../modules/juce_graphics/native/juce_mac_CoreGraphicsHelpers.h\
  ../../../../../modules/juce_graphics/native/juce_mac_Fonts.mm\
  ../../../../../modules/juce_graphics/native/juce_RenderingHelpers.h\
  ../../../../../modules/juce_graphics/native/juce_win32_Direct2DGraphicsContext.cpp\
  ../../../../../modules/juce_graphics/native/juce_win32_DirectWriteTypeface.cpp\
  ../../../../../modules/juce_graphics/native/juce_win32_DirectWriteTypeLayout.cpp\
  ../../../../../modules/juce_graphics/native/juce_win32_Fonts.cpp\
  ../../../../../modules/juce_graphics/juce_module_info\
  ../../../../../modules/juce_graphics/juce_graphics.h\
  ../../../../../modules/juce_gui_basics/components/juce_CachedComponentImage.h\
  ../../../../../modules/juce_gui_basics/components/juce_Component.cpp\
  ../../../../../modules/juce_gui_basics/components/juce_Component.h\
  ../../../../../modules/juce_gui_basics/components/juce_ComponentListener.cpp\
  ../../../../../modules/juce_gui_basics/components/juce_ComponentListener.h\
  ../../../../../modules/juce_gui_basics/components/juce_Desktop.cpp\
  ../../../../../modules/juce_gui_basics/components/juce_Desktop.h\
  ../../../../../modules/juce_gui_basics/components/juce_ModalComponentManager.cpp\
  ../../../../../modules/juce_gui_basics/components/juce_ModalComponentManager.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_ComponentDragger.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_ComponentDragger.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_DragAndDropContainer.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_DragAndDropContainer.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_DragAndDropTarget.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_FileDragAndDropTarget.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_LassoComponent.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseCursor.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseCursor.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseEvent.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseEvent.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseInactivityDetector.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseInactivityDetector.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseInputSource.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseListener.cpp\
  ../../../../../modules/juce_gui_basics/mouse/juce_MouseListener.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_SelectedItemSet.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_TextDragAndDropTarget.h\
  ../../../../../modules/juce_gui_basics/mouse/juce_TooltipClient.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_CaretComponent.cpp\
  ../../../../../modules/juce_gui_basics/keyboard/juce_CaretComponent.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyboardFocusTraverser.cpp\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyboardFocusTraverser.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyListener.cpp\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyListener.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyPress.cpp\
  ../../../../../modules/juce_gui_basics/keyboard/juce_KeyPress.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_ModifierKeys.cpp\
  ../../../../../modules/juce_gui_basics/keyboard/juce_ModifierKeys.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_SystemClipboard.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_TextEditorKeyMapper.h\
  ../../../../../modules/juce_gui_basics/keyboard/juce_TextInputTarget.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ComboBox.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ComboBox.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ImageComponent.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ImageComponent.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_Label.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_Label.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ListBox.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ListBox.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ProgressBar.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ProgressBar.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_Slider.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_Slider.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_TableHeaderComponent.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_TableHeaderComponent.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_TableListBox.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_TableListBox.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_TextEditor.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_TextEditor.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_Toolbar.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_Toolbar.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ToolbarItemComponent.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ToolbarItemComponent.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ToolbarItemFactory.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_ToolbarItemPalette.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_ToolbarItemPalette.h\
  ../../../../../modules/juce_gui_basics/widgets/juce_TreeView.cpp\
  ../../../../../modules/juce_gui_basics/widgets/juce_TreeView.h\
  ../../../../../modules/juce_gui_basics/windows/juce_AlertWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_AlertWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_CallOutBox.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_CallOutBox.h\
  ../../../../../modules/juce_gui_basics/windows/juce_ComponentPeer.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_ComponentPeer.h\
  ../../../../../modules/juce_gui_basics/windows/juce_DialogWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_DialogWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_DocumentWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_DocumentWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_NativeMessageBox.h\
  ../../../../../modules/juce_gui_basics/windows/juce_ResizableWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_ResizableWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_ThreadWithProgressWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_ThreadWithProgressWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_TooltipWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_TooltipWindow.h\
  ../../../../../modules/juce_gui_basics/windows/juce_TopLevelWindow.cpp\
  ../../../../../modules/juce_gui_basics/windows/juce_TopLevelWindow.h\
  ../../../../../modules/juce_gui_basics/menus/juce_MenuBarComponent.cpp\
  ../../../../../modules/juce_gui_basics/menus/juce_MenuBarComponent.h\
  ../../../../../modules/juce_gui_basics/menus/juce_MenuBarModel.cpp\
  ../../../../../modules/juce_gui_basics/menus/juce_MenuBarModel.h\
  ../../../../../modules/juce_gui_basics/menus/juce_PopupMenu.cpp\
  ../../../../../modules/juce_gui_basics/menus/juce_PopupMenu.h\
  ../../../../../modules/juce_gui_basics/layout/juce_AnimatedPosition.h\
  ../../../../../modules/juce_gui_basics/layout/juce_AnimatedPositionBehaviours.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentAnimator.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentAnimator.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentBoundsConstrainer.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentBoundsConstrainer.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentBuilder.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentBuilder.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentMovementWatcher.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ComponentMovementWatcher.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ConcertinaPanel.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ConcertinaPanel.h\
  ../../../../../modules/juce_gui_basics/layout/juce_GroupComponent.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_GroupComponent.h\
  ../../../../../modules/juce_gui_basics/layout/juce_MultiDocumentPanel.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_MultiDocumentPanel.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableBorderComponent.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableBorderComponent.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableCornerComponent.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableCornerComponent.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableEdgeComponent.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ResizableEdgeComponent.h\
  ../../../../../modules/juce_gui_basics/layout/juce_ScrollBar.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_ScrollBar.h\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableLayoutManager.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableLayoutManager.h\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableLayoutResizerBar.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableLayoutResizerBar.h\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableObjectResizer.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_StretchableObjectResizer.h\
  ../../../../../modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_TabbedButtonBar.h\
  ../../../../../modules/juce_gui_basics/layout/juce_TabbedComponent.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_TabbedComponent.h\
  ../../../../../modules/juce_gui_basics/layout/juce_Viewport.cpp\
  ../../../../../modules/juce_gui_basics/layout/juce_Viewport.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_ArrowButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_ArrowButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_Button.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_Button.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_DrawableButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_DrawableButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_HyperlinkButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_HyperlinkButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_ImageButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_ImageButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_ShapeButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_ShapeButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_TextButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_TextButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_ToggleButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_ToggleButton.h\
  ../../../../../modules/juce_gui_basics/buttons/juce_ToolbarButton.cpp\
  ../../../../../modules/juce_gui_basics/buttons/juce_ToolbarButton.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_MarkerList.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_MarkerList.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeCoordinate.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeCoordinate.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeCoordinatePositioner.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeCoordinatePositioner.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeParallelogram.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeParallelogram.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativePoint.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativePoint.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativePointPath.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativePointPath.h\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeRectangle.cpp\
  ../../../../../modules/juce_gui_basics/positioning/juce_RelativeRectangle.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_Drawable.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_Drawable.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableComposite.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableComposite.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableImage.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableImage.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawablePath.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawablePath.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableRectangle.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableRectangle.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableShape.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableShape.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableText.cpp\
  ../../../../../modules/juce_gui_basics/drawables/juce_DrawableText.h\
  ../../../../../modules/juce_gui_basics/drawables/juce_SVGParser.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_BooleanPropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_BooleanPropertyComponent.h\
  ../../../../../modules/juce_gui_basics/properties/juce_ButtonPropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_ButtonPropertyComponent.h\
  ../../../../../modules/juce_gui_basics/properties/juce_ChoicePropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_ChoicePropertyComponent.h\
  ../../../../../modules/juce_gui_basics/properties/juce_PropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_PropertyComponent.h\
  ../../../../../modules/juce_gui_basics/properties/juce_PropertyPanel.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_PropertyPanel.h\
  ../../../../../modules/juce_gui_basics/properties/juce_SliderPropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_SliderPropertyComponent.h\
  ../../../../../modules/juce_gui_basics/properties/juce_TextPropertyComponent.cpp\
  ../../../../../modules/juce_gui_basics/properties/juce_TextPropertyComponent.h\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel.cpp\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel.h\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V1.cpp\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V1.h\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V2.cpp\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V2.h\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V3.cpp\
  ../../../../../modules/juce_gui_basics/lookandfeel/juce_LookAndFeel_V3.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_DirectoryContentsDisplayComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_DirectoryContentsDisplayComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_DirectoryContentsList.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileBrowserComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileBrowserComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileBrowserListener.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileChooser.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileChooser.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileChooserDialogBox.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileChooserDialogBox.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileListComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileListComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FilenameComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FilenameComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FilePreviewComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileSearchPathListComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileSearchPathListComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileTreeComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_FileTreeComponent.h\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_ImagePreviewComponent.cpp\
  ../../../../../modules/juce_gui_basics/filebrowser/juce_ImagePreviewComponent.h\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandID.h\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandInfo.cpp\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandInfo.h\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandManager.cpp\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandManager.h\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandTarget.cpp\
  ../../../../../modules/juce_gui_basics/commands/juce_ApplicationCommandTarget.h\
  ../../../../../modules/juce_gui_basics/commands/juce_KeyPressMappingSet.cpp\
  ../../../../../modules/juce_gui_basics/commands/juce_KeyPressMappingSet.h\
  ../../../../../modules/juce_gui_basics/misc/juce_BubbleComponent.cpp\
  ../../../../../modules/juce_gui_basics/misc/juce_BubbleComponent.h\
  ../../../../../modules/juce_gui_basics/misc/juce_DropShadower.cpp\
  ../../../../../modules/juce_gui_basics/misc/juce_DropShadower.h\
  ../../../../../modules/juce_gui_basics/application/juce_Application.cpp\
  ../../../../../modules/juce_gui_basics/application/juce_Application.h\
  ../../../../../modules/juce_gui_basics/native/juce_android_FileChooser.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_android_Windowing.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_ios_UIViewComponentPeer.mm\
  ../../../../../modules/juce_gui_basics/native/juce_ios_Windowing.mm\
  ../../../../../modules/juce_gui_basics/native/juce_linux_Clipboard.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_linux_FileChooser.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_linux_Windowing.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_mac_FileChooser.mm\
  ../../../../../modules/juce_gui_basics/native/juce_mac_MainMenu.mm\
  ../../../../../modules/juce_gui_basics/native/juce_mac_MouseCursor.mm\
  ../../../../../modules/juce_gui_basics/native/juce_mac_NSViewComponentPeer.mm\
  ../../../../../modules/juce_gui_basics/native/juce_mac_Windowing.mm\
  ../../../../../modules/juce_gui_basics/native/juce_MultiTouchMapper.h\
  ../../../../../modules/juce_gui_basics/native/juce_win32_DragAndDrop.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_win32_FileChooser.cpp\
  ../../../../../modules/juce_gui_basics/native/juce_win32_Windowing.cpp\
  ../../../../../modules/juce_gui_basics/juce_module_info\
  ../../../../../modules/juce_gui_basics/juce_gui_basics.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CodeDocument.cpp\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CodeDocument.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CodeEditorComponent.cpp\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CodeEditorComponent.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CodeTokeniser.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniser.cpp\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniser.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_CPlusPlusCodeTokeniserFunctions.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_LuaCodeTokeniser.cpp\
  ../../../../../modules/juce_gui_extra/code_editor/juce_LuaCodeTokeniser.h\
  ../../../../../modules/juce_gui_extra/code_editor/juce_XMLCodeTokeniser.cpp\
  ../../../../../modules/juce_gui_extra/code_editor/juce_XMLCodeTokeniser.h\
  ../../../../../modules/juce_gui_extra/documents/juce_FileBasedDocument.cpp\
  ../../../../../modules/juce_gui_extra/documents/juce_FileBasedDocument.h\
  ../../../../../modules/juce_gui_extra/embedding/juce_ActiveXControlComponent.h\
  ../../../../../modules/juce_gui_extra/embedding/juce_NSViewComponent.h\
  ../../../../../modules/juce_gui_extra/embedding/juce_UIViewComponent.h\
  ../../../../../modules/juce_gui_extra/misc/juce_AnimatedAppComponent.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_AnimatedAppComponent.h\
  ../../../../../modules/juce_gui_extra/misc/juce_AppleRemote.h\
  ../../../../../modules/juce_gui_extra/misc/juce_BubbleMessageComponent.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_BubbleMessageComponent.h\
  ../../../../../modules/juce_gui_extra/misc/juce_ColourSelector.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_ColourSelector.h\
  ../../../../../modules/juce_gui_extra/misc/juce_KeyMappingEditorComponent.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_KeyMappingEditorComponent.h\
  ../../../../../modules/juce_gui_extra/misc/juce_LiveConstantEditor.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_LiveConstantEditor.h\
  ../../../../../modules/juce_gui_extra/misc/juce_PreferencesPanel.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_PreferencesPanel.h\
  ../../../../../modules/juce_gui_extra/misc/juce_RecentlyOpenedFilesList.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_RecentlyOpenedFilesList.h\
  ../../../../../modules/juce_gui_extra/misc/juce_SplashScreen.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_SplashScreen.h\
  ../../../../../modules/juce_gui_extra/misc/juce_SystemTrayIconComponent.cpp\
  ../../../../../modules/juce_gui_extra/misc/juce_SystemTrayIconComponent.h\
  ../../../../../modules/juce_gui_extra/misc/juce_WebBrowserComponent.h\
  ../../../../../modules/juce_gui_extra/native/juce_android_WebBrowserComponent.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_ios_UIViewComponent.mm\
  ../../../../../modules/juce_gui_extra/native/juce_linux_SystemTrayIcon.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_linux_WebBrowserComponent.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_mac_AppleRemote.mm\
  ../../../../../modules/juce_gui_extra/native/juce_mac_CarbonViewWrapperComponent.h\
  ../../../../../modules/juce_gui_extra/native/juce_mac_NSViewComponent.mm\
  ../../../../../modules/juce_gui_extra/native/juce_mac_SystemTrayIcon.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_mac_WebBrowserComponent.mm\
  ../../../../../modules/juce_gui_extra/native/juce_win32_ActiveXComponent.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_win32_SystemTrayIcon.cpp\
  ../../../../../modules/juce_gui_extra/native/juce_win32_WebBrowserComponent.cpp\
  ../../../../../modules/juce_gui_extra/juce_module_info\
  ../../../../../modules/juce_gui_extra/juce_gui_extra.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLContext.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLContext.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLFrameBuffer.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLFrameBuffer.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLGraphicsContext.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLGraphicsContext.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLHelpers.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLHelpers.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLImage.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLImage.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLPixelFormat.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLPixelFormat.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLRenderer.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLShaderProgram.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLShaderProgram.h\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLTexture.cpp\
  ../../../../../modules/juce_opengl/opengl/juce_OpenGLTexture.h\
  ../../../../../modules/juce_opengl/geometry/juce_Draggable3DOrientation.h\
  ../../../../../modules/juce_opengl/geometry/juce_Matrix3D.h\
  ../../../../../modules/juce_opengl/geometry/juce_Quaternion.h\
  ../../../../../modules/juce_opengl/geometry/juce_Vector3D.h\
  ../../../../../modules/juce_opengl/utils/juce_OpenGLAppComponent.cpp\
  ../../../../../modules/juce_opengl/utils/juce_OpenGLAppComponent.h\
  ../../../../../modules/juce_opengl/native/juce_MissingGLDefinitions.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGL_android.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGL_ios.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGL_linux.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGL_osx.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGL_win32.h\
  ../../../../../modules/juce_opengl/native/juce_OpenGLExtensions.h\
  ../../../../../modules/juce_opengl/juce_module_info\
  ../../../../../modules/juce_opengl/juce_opengl.h\
  ../../../../../modules/juce_video/playback/juce_DirectShowComponent.h\
  ../../../../../modules/juce_video/playback/juce_QuickTimeMovieComponent.h\
  ../../../../../modules/juce_video/capture/juce_CameraDevice.cpp\
  ../../../../../modules/juce_video/capture/juce_CameraDevice.h\
  ../../../../../modules/juce_video/native/juce_android_CameraDevice.cpp\
  ../../../../../modules/juce_video/native/juce_mac_CameraDevice.mm\
  ../../../../../modules/juce_video/native/juce_mac_QuickTimeMovieComponent.mm\
  ../../../../../modules/juce_video/native/juce_win32_CameraDevice.cpp\
  ../../../../../modules/juce_video/native/juce_win32_DirectShowComponent.cpp\
  ../../../../../modules/juce_video/native/juce_win32_QuickTimeMovieComponent.cpp\
  ../../../../../modules/juce_video/juce_module_info\
  ../../../../../modules/juce_video/juce_video.h\
  ../../../JuceLibraryCode/AppConfig.h\
  ../../../JuceLibraryCode/BinaryData.cpp\
  ../../../JuceLibraryCode/BinaryData.h\
  ../../../../../modules/juce_audio_basics/juce_audio_basics.cpp\
  ../../../../../modules/juce_audio_devices/juce_audio_devices.cpp\
  ../../../../../modules/juce_audio_formats/juce_audio_formats.cpp\
  ../../../../../modules/juce_audio_processors/juce_audio_processors.cpp\
  ../../../../../modules/juce_audio_utils/juce_audio_utils.cpp\
  ../../../../../modules/juce_box2d/juce_box2d.cpp\
  ../../../../../modules/juce_core/juce_core.cpp\
  ../../../../../modules/juce_cryptography/juce_cryptography.cpp\
  ../../../../../modules/juce_data_structures/juce_data_structures.cpp\
  ../../../../../modules/juce_events/juce_events.cpp\
  ../../../../../modules/juce_graphics/juce_graphics.cpp\
  ../../../../../modules/juce_gui_basics/juce_gui_basics.cpp\
  ../../../../../modules/juce_gui_extra/juce_gui_extra.cpp\
  ../../../../../modules/juce_opengl/juce_opengl.cpp\
  ../../../../../modules/juce_video/juce_video.cpp\
  ../../../JuceLibraryCode/JuceHeader.h\

ifeq ($(NDK_DEBUG),1)
  LOCAL_CPPFLAGS += -fsigned-char -fexceptions -frtti -g -I "../../JuceLibraryCode" -I "../../../../modules" -O0 -std=c++11 -std=gnu++11 -D "JUCE_ANDROID=1" -D "JUCE_ANDROID_API_VERSION=9" -D "JUCE_ANDROID_ACTIVITY_CLASSNAME=com_juce_jucedemo_JuceDemo" -D JUCE_ANDROID_ACTIVITY_CLASSPATH=\"com/juce/jucedemo/JuceDemo\" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCE_UNIT_TESTS=1" -D "JUCER_ANDROID_7F0E4A25=1" -D "JUCE_APP_VERSION=3.0.0" -D "JUCE_APP_VERSION_HEX=0x30000"
  LOCAL_LDLIBS := -llog -lGLESv2
  LOCAL_CFLAGS += -fsigned-char -fexceptions -frtti -g -I "../../JuceLibraryCode" -I "../../../../modules" -O0 -std=c++11 -std=gnu++11 -D "JUCE_ANDROID=1" -D "JUCE_ANDROID_API_VERSION=9" -D "JUCE_ANDROID_ACTIVITY_CLASSNAME=com_juce_jucedemo_JuceDemo" -D JUCE_ANDROID_ACTIVITY_CLASSPATH=\"com/juce/jucedemo/JuceDemo\" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCE_UNIT_TESTS=1" -D "JUCER_ANDROID_7F0E4A25=1" -D "JUCE_APP_VERSION=3.0.0" -D "JUCE_APP_VERSION_HEX=0x30000"
  LOCAL_LDLIBS := -llog -lGLESv2
else
  LOCAL_CPPFLAGS += -fsigned-char -fexceptions -frtti -I "../../JuceLibraryCode" -I "../../../../modules" -O3 -std=c++11 -std=gnu++11 -D "JUCE_ANDROID=1" -D "JUCE_ANDROID_API_VERSION=9" -D "JUCE_ANDROID_ACTIVITY_CLASSNAME=com_juce_jucedemo_JuceDemo" -D JUCE_ANDROID_ACTIVITY_CLASSPATH=\"com/juce/jucedemo/JuceDemo\" -D "NDEBUG=1" -D "JUCE_UNIT_TESTS=1" -D "JUCER_ANDROID_7F0E4A25=1" -D "JUCE_APP_VERSION=3.0.0" -D "JUCE_APP_VERSION_HEX=0x30000"
  LOCAL_LDLIBS := -llog -lGLESv2
  LOCAL_CFLAGS += -fsigned-char -fexceptions -frtti -I "../../JuceLibraryCode" -I "../../../../modules" -O3 -std=c++11 -std=gnu++11 -D "JUCE_ANDROID=1" -D "JUCE_ANDROID_API_VERSION=9" -D "JUCE_ANDROID_ACTIVITY_CLASSNAME=com_juce_jucedemo_JuceDemo" -D JUCE_ANDROID_ACTIVITY_CLASSPATH=\"com/juce/jucedemo/JuceDemo\" -D "NDEBUG=1" -D "JUCE_UNIT_TESTS=1" -D "JUCER_ANDROID_7F0E4A25=1" -D "JUCE_APP_VERSION=3.0.0" -D "JUCE_APP_VERSION_HEX=0x30000"
  LOCAL_LDLIBS := -llog -lGLESv2
endif

include $(BUILD_SHARED_LIBRARY)
