/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    This is the header file that your files should include in order to get all the
    Juce library headers. You should NOT include juce.h or juce_amalgamated.h directly in
    your own source files, because that wouldn't pick up the correct Juce configuration
    options for your app.

*/

#ifndef __APPHEADERFILE_C6E440F8__
#define __APPHEADERFILE_C6E440F8__

#include "AppConfig.h"
#include "../../../juce_amalgamated.h"
#include "BinaryData.h"

namespace ProjectInfo
{
    const char* const  projectName    = "Juce Demo";
    const char* const  versionString  = "1.0.0";
    const int          versionNumber  = 0x10000;
}

#endif   // __APPHEADERFILE_C6E440F8__
