/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file, created by The Jucer V3.0.0
   Do not edit anything in this file!

*/

#include "BinaryData.h"


const char* BinaryData::getNamedResource (const char* resourceNameUTF8, int& numBytes) throw()
{
    int hash = 0;
    if (resourceNameUTF8 != 0)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + *resourceNameUTF8++;

    switch (hash)
    {
        case 0x44be9398:  numBytes = BinaryData::AudioPluginXCodeScript_txtSize; return BinaryData::AudioPluginXCodeScript_txt;
        case 0x27c5a93a:  numBytes = BinaryData::jucer_AudioPluginEditorTemplate_cppSize; return BinaryData::jucer_AudioPluginEditorTemplate_cpp;
        case 0x4d0721bf:  numBytes = BinaryData::jucer_AudioPluginEditorTemplate_hSize; return BinaryData::jucer_AudioPluginEditorTemplate_h;
        case 0x51b49ac5:  numBytes = BinaryData::jucer_AudioPluginFilterTemplate_cppSize; return BinaryData::jucer_AudioPluginFilterTemplate_cpp;
        case 0x488afa0a:  numBytes = BinaryData::jucer_AudioPluginFilterTemplate_hSize; return BinaryData::jucer_AudioPluginFilterTemplate_h;
        case 0xabad7041:  numBytes = BinaryData::jucer_ComponentTemplate_cppSize; return BinaryData::jucer_ComponentTemplate_cpp;
        case 0xfc72fe86:  numBytes = BinaryData::jucer_ComponentTemplate_hSize; return BinaryData::jucer_ComponentTemplate_h;
        case 0x8905395b:  numBytes = BinaryData::jucer_MainConsoleAppTemplate_cppSize; return BinaryData::jucer_MainConsoleAppTemplate_cpp;
        case 0x7a0186b1:  numBytes = BinaryData::jucer_MainTemplate_cppSize; return BinaryData::jucer_MainTemplate_cpp;
        case 0x02a2a077:  numBytes = BinaryData::jucer_NewCppFileTemplate_cppSize; return BinaryData::jucer_NewCppFileTemplate_cpp;
        case 0x0842c43c:  numBytes = BinaryData::jucer_NewCppFileTemplate_hSize; return BinaryData::jucer_NewCppFileTemplate_h;
        case 0x3f052be8:  numBytes = BinaryData::jucer_WindowTemplate_cppSize; return BinaryData::jucer_WindowTemplate_cpp;
        case 0xb20377ed:  numBytes = BinaryData::jucer_WindowTemplate_hSize; return BinaryData::jucer_WindowTemplate_h;
        case 0x154a7275:  numBytes = BinaryData::juce_icon_pngSize; return BinaryData::juce_icon_png;
        default: break;
    }

    numBytes = 0;
    return 0;
}


//================== AudioPluginXCodeScript.txt ==================
static const unsigned char temp_198ab1e7[] =
"\r\n"
"# This script takes the build product and copies it to the AU, VST, and RTAS folders, depending on \r\n"
"# which plugin types you've built\r\n"
"\r\n"
"original=$CONFIGURATION_BUILD_DIR/$FULL_PRODUCT_NAME\r\n"
"\r\n"
"# this looks inside the binary to detect which platforms are needed.. \r\n"
"copyAU=`nm -g \"$CONFIGURATION_BUILD_DIR/$EXECUTABLE_PATH\" | grep -i 'AudioUnit' | wc -l`\r\n"
"copyVST=`nm -g \"$CONFIGURATION_BUILD_DIR/$EXECUTABLE_PATH\" | grep -i 'VSTPlugin' | wc -l`\r\n"
"copyRTAS=`nm -g \"$CONFIGURATION_BUILD_DIR/$EXECUTABLE_PATH\" | grep -i 'CProcess' | wc -l`\r\n"
"\r\n"
"if [ $copyAU -gt 0 ]; then\r\n"
"  echo \"Copying to AudioUnit folder...\"\r\n"
"  AU=~/Library/Audio/Plug-Ins/Components/$PRODUCT_NAME.component\r\n"
"  if [ -d \"$AU\" ]; then \r\n"
"    rm -r \"$AU\"\r\n"
"  fi\r\n"
"\r\n"
"  cp -r \"$original\" \"$AU\"\r\n"
"  sed -i \"\" -e 's/TDMwPTul/BNDLPTul/g' \"$AU/Contents/PkgInfo\"\r\n"
"  sed -i \"\" -e 's/TDMw/BNDL/g' \"$AU/Contents/$INFOPLIST_FILE\"\r\n"
"fi\r\n"
"\r\n"
"if [ $copyVST -gt 0 ]; then\r\n"
"  echo \"Copying to VST folder...\"\r\n"
"  VST=~/Library/Audio/Plug-Ins/VST/$PRODUCT_NAME.vst\r\n"
"  if [ -d \"$VST\" ]; then \r\n"
"    rm -r \"$VST\"\r\n"
"  fi\r\n"
"\r\n"
"  cp -r \"$original\" \"$VST\"\r\n"
"  sed -i \"\" -e 's/TDMwPTul/BNDLPTul/g' \"$VST/Contents/PkgInfo\"\r\n"
"  sed -i \"\" -e 's/TDMw/BNDL/g' \"$VST/Contents/$INFOPLIST_FILE\"\r\n"
"fi\r\n"
"\r\n"
"if [ $copyRTAS -gt 0 ]; then\r\n"
"  echo \"Copying to RTAS folder...\"\r\n"
"  RTAS=/Library/Application\\ Support/Digidesign/Plug-Ins/$PRODUCT_NAME.dpm\r\n"
"  if [ -d \"$RTAS\" ]; then\r\n"
"    rm -r \"$RTAS\"\r\n"
"  fi\r\n"
"\r\n"
"  cp -r \"$original\" \"$RTAS\"\r\n"
"fi\r\n";

const char* BinaryData::AudioPluginXCodeScript_txt = (const char*) temp_198ab1e7;

//================== jucer_AudioPluginEditorTemplate.cpp ==================
static const unsigned char temp_9d632c4d[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"EDITORCPPHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"EDITORCLASSNAME::EDITORCLASSNAME (FILTERCLASSNAME* ownerFilter)\r\n"
"    : AudioProcessorEditor (ownerFilter)\r\n"
"{\r\n"
"    // This is where our plugin's editor size is set.\r\n"
"    setSize (400, 300);\r\n"
"}\r\n"
"\r\n"
"EDITORCLASSNAME::~EDITORCLASSNAME()\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"void EDITORCLASSNAME::paint (Graphics& g)\r\n"
"{\r\n"
"    g.fillAll (Colours::white);\r\n"
"    g.setColour (Colours::black);\r\n"
"    g.setFont (15.0f);\r\n"
"    g.drawFittedText (\"Hello World!\",\r\n"
"                      0, 0, getWidth(), getHeight(),\r\n"
"                      Justification::centred, 1);\r\n"
"}\r\n";

const char* BinaryData::jucer_AudioPluginEditorTemplate_cpp = (const char*) temp_9d632c4d;

//================== jucer_AudioPluginEditorTemplate.h ==================
static const unsigned char temp_ac404d92[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"#ifndef HEADERGUARD\r\n"
"#define HEADERGUARD\r\n"
"\r\n"
"EDITORHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"/**\r\n"
"*/\r\n"
"class EDITORCLASSNAME  : public AudioProcessorEditor\r\n"
"{\r\n"
"public:\r\n"
"    EDITORCLASSNAME (FILTERCLASSNAME* ownerFilter);\r\n"
"    ~EDITORCLASSNAME();\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    // This is just a standard Juce paint method...\r\n"
"    void paint (Graphics& g);\r\n"
"};\r\n"
"\r\n"
"\r\n"
"#endif  // HEADERGUARD\r\n";

const char* BinaryData::jucer_AudioPluginEditorTemplate_h = (const char*) temp_ac404d92;

//================== jucer_AudioPluginFilterTemplate.cpp ==================
static const unsigned char temp_c7521dd8[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"FILTERHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"FILTERCLASSNAME::FILTERCLASSNAME()\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"FILTERCLASSNAME::~FILTERCLASSNAME()\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"const String FILTERCLASSNAME::getName() const\r\n"
"{\r\n"
"    return JucePlugin_Name;\r\n"
"}\r\n"
"\r\n"
"int FILTERCLASSNAME::getNumParameters()\r\n"
"{\r\n"
"    return 0;\r\n"
"}\r\n"
"\r\n"
"float FILTERCLASSNAME::getParameter (int index)\r\n"
"{\r\n"
"    return 0.0f;\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::setParameter (int index, float newValue)\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"const String FILTERCLASSNAME::getParameterName (int index)\r\n"
"{\r\n"
"    return String::empty;\r\n"
"}\r\n"
"\r\n"
"const String FILTERCLASSNAME::getParameterText (int index)\r\n"
"{\r\n"
"    return String::empty;\r\n"
"}\r\n"
"\r\n"
"const String FILTERCLASSNAME::getInputChannelName (const int channelIndex) const\r\n"
"{\r\n"
"    return String (channelIndex + 1);\r\n"
"}\r\n"
"\r\n"
"const String FILTERCLASSNAME::getOutputChannelName (const int channelIndex) const\r\n"
"{\r\n"
"    return String (channelIndex + 1);\r\n"
"}\r\n"
"\r\n"
"bool FILTERCLASSNAME::isInputChannelStereoPair (int index) const\r\n"
"{\r\n"
"    return true;\r\n"
"}\r\n"
"\r\n"
"bool FILTERCLASSNAME::isOutputChannelStereoPair (int index) const\r\n"
"{\r\n"
"    return true;\r\n"
"}\r\n"
"\r\n"
"bool FILTERCLASSNAME::acceptsMidi() const\r\n"
"{\r\n"
"#if JucePlugin_WantsMidiInput\r\n"
"    return true;\r\n"
"#else\r\n"
"    return false;\r\n"
"#endif\r\n"
"}\r\n"
"\r\n"
"bool FILTERCLASSNAME::producesMidi() const\r\n"
"{\r\n"
"#if JucePlugin_ProducesMidiOutput\r\n"
"    return true;\r\n"
"#else\r\n"
"    return false;\r\n"
"#endif\r\n"
"}\r\n"
"\r\n"
"int FILTERCLASSNAME::getNumPrograms()\r\n"
"{\r\n"
"    return 0;\r\n"
"}\r\n"
"\r\n"
"int FILTERCLASSNAME::getCurrentProgram()\r\n"
"{\r\n"
"    return 0;\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::setCurrentProgram (int index)\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"const String FILTERCLASSNAME::getProgramName (int index)\r\n"
"{\r\n"
"    return String::empty;\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::changeProgramName (int index, const String& newName)\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"void FILTERCLASSNAME::prepareToPlay (double sampleRate, int samplesPerBlock)\r\n"
"{\r\n"
"    // Use this method as the place to do any pre-playback\r\n"
"    // initialisation that you need..\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::releaseResources()\r\n"
"{\r\n"
"    // When playback stops, you can use this as an opportunity to free up any\r\n"
"    // spare memory, etc.\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)\r\n"
"{\r\n"
"    // This is the place where you'd normally do the guts of your plugin's\r\n"
"    // audio processing...\r\n"
"    for (int channel = 0; channel < getNumInputChannels(); ++channel)\r\n"
"    {\r\n"
"        float* channelData = buffer.getSampleData (channel);\r\n"
"\r\n"
"        // ..do something to the data...\r\n"
"    }\r\n"
"\r\n"
"    // In case we have more outputs than inputs, we'll clear any output\r\n"
"    // channels that didn't contain input data, (because these aren't\r\n"
"    // guaranteed to be empty - they may contain garbage).\r\n"
"    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)\r\n"
"    {\r\n"
"        buffer.clear (i, 0, buffer.getNumSamples());\r\n"
"    }\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"AudioProcessorEditor* FILTERCLASSNAME::createEditor()\r\n"
"{\r\n"
"    return new EDITORCLASSNAME (this);\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"void FILTERCLASSNAME::getStateInformation (MemoryBlock& destData)\r\n"
"{\r\n"
"    // You should use this method to store your parameters in the memory block.\r\n"
"    // You could do that either as raw data, or use the XML or ValueTree classes\r\n"
"    // as intermediaries to make it easy to save and load complex data.\r\n"
"}\r\n"
"\r\n"
"void FILTERCLASSNAME::setStateInformation (const void* data, int sizeInBytes)\r\n"
"{\r\n"
"    // You should use this method to restore your parameters from this memory block,\r\n"
"    // whose contents will have been created by the getStateInformation() call.\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"// This creates new instances of the plugin..\r\n"
"AudioProcessor* JUCE_CALLTYPE createPluginFilter()\r\n"
"{\r\n"
"    return new FILTERCLASSNAME();\r\n"
"}\r\n";

const char* BinaryData::jucer_AudioPluginFilterTemplate_cpp = (const char*) temp_c7521dd8;

//================== jucer_AudioPluginFilterTemplate.h ==================
static const unsigned char temp_a7c425dd[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"#ifndef HEADERGUARD\r\n"
"#define HEADERGUARD\r\n"
"\r\n"
"APPHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"/**\r\n"
"*/\r\n"
"class FILTERCLASSNAME  : public AudioProcessor\r\n"
"{\r\n"
"public:\r\n"
"    //==============================================================================\r\n"
"    FILTERCLASSNAME();\r\n"
"    ~FILTERCLASSNAME();\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    void prepareToPlay (double sampleRate, int samplesPerBlock);\r\n"
"    void releaseResources();\r\n"
"\r\n"
"    void processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages);\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    AudioProcessorEditor* createEditor();\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    const String getName() const;\r\n"
"\r\n"
"    int getNumParameters();\r\n"
"\r\n"
"    float getParameter (int index);\r\n"
"    void setParameter (int index, float newValue);\r\n"
"\r\n"
"    const String getParameterName (int index);\r\n"
"    const String getParameterText (int index);\r\n"
"\r\n"
"    const String getInputChannelName (const int channelIndex) const;\r\n"
"    const String getOutputChannelName (const int channelIndex) const;\r\n"
"    bool isInputChannelStereoPair (int index) const;\r\n"
"    bool isOutputChannelStereoPair (int index) const;\r\n"
"\r\n"
"    bool acceptsMidi() const;\r\n"
"    bool producesMidi() const;\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    int getNumPrograms();\r\n"
"    int getCurrentProgram();\r\n"
"    void setCurrentProgram (int index);\r\n"
"    const String getProgramName (int index);\r\n"
"    void changeProgramName (int index, const String& newName);\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    void getStateInformation (MemoryBlock& destData);\r\n"
"    void setStateInformation (const void* data, int sizeInBytes);\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    juce_UseDebuggingNewOperator\r\n"
"\r\n"
"};\r\n"
"\r\n"
"#endif  // HEADERGUARD\r\n";

const char* BinaryData::jucer_AudioPluginFilterTemplate_h = (const char*) temp_a7c425dd;

//================== jucer_ComponentTemplate.cpp ==================
static const unsigned char temp_73015554[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"  This is an automatically generated file created by the Jucer!\r\n"
"\r\n"
"  Creation date:  %%creationTime%%\r\n"
"\r\n"
"  Be careful when adding custom code to these files, as only the code within\r\n"
"  the \"//[xyz]\" and \"//[/xyz]\" sections will be retained when the file is loaded\r\n"
"  and re-saved.\r\n"
"\r\n"
"  Jucer version: 1.12\r\n"
"\r\n"
"  ------------------------------------------------------------------------------\r\n"
"\r\n"
"  The Jucer is part of the JUCE library - \"Jules' Utility Class Extensions\"\r\n"
"  Copyright 2004-6 by Raw Material Software ltd.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"//[Headers] You can add your own extra header files here...\r\n"
"//[/Headers]\r\n"
"\r\n"
"%%includeFilesCPP%%\r\n"
"\r\n"
"//[MiscUserDefs] You can add your own user definitions and misc code here...\r\n"
"//[/MiscUserDefs]\r\n"
"\r\n"
"//==============================================================================\r\n"
"%%className%%::%%className%% (%%constructorParams%%)\r\n"
"%%initialisers%%{\r\n"
"    %%constructor%%\r\n"
"\r\n"
"    //[Constructor] You can add your own custom stuff here..\r\n"
"    //[/Constructor]\r\n"
"}\r\n"
"\r\n"
"%%className%%::~%%className%%()\r\n"
"{\r\n"
"    //[Destructor_pre]. You can add your own custom destruction code here..\r\n"
"    //[/Destructor_pre]\r\n"
"\r\n"
"    %%destructor%%\r\n"
"\r\n"
"    //[Destructor]. You can add your own custom destruction code here..\r\n"
"    //[/Destructor]\r\n"
"}\r\n"
"\r\n"
"//==============================================================================\r\n"
"%%methodDefinitions%%\r\n"
"\r\n"
"//[MiscUserCode] You can add your own definitions of your custom methods or any other code here...\r\n"
"//[/MiscUserCode]\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"#if 0\r\n"
"/*  -- Jucer information section --\r\n"
"\r\n"
"    This is where the Jucer puts all of its metadata, so don't change anything in here!\r\n"
"\r\n"
"BEGIN_JUCER_METADATA\r\n"
"\r\n"
"%%metadata%%\r\n"
"END_JUCER_METADATA\r\n"
"*/\r\n"
"#endif\r\n"
"\r\n"
"%%staticMemberDefinitions%%\r\n";

const char* BinaryData::jucer_ComponentTemplate_cpp = (const char*) temp_73015554;

//================== jucer_ComponentTemplate.h ==================
static const unsigned char temp_b930c59[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"  This is an automatically generated file created by the Jucer!\r\n"
"\r\n"
"  Creation date:  %%creationTime%%\r\n"
"\r\n"
"  Be careful when adding custom code to these files, as only the code within\r\n"
"  the \"//[xyz]\" and \"//[/xyz]\" sections will be retained when the file is loaded\r\n"
"  and re-saved.\r\n"
"\r\n"
"  Jucer version: 1.12\r\n"
"\r\n"
"  ------------------------------------------------------------------------------\r\n"
"\r\n"
"  The Jucer is part of the JUCE library - \"Jules' Utility Class Extensions\"\r\n"
"  Copyright 2004-6 by Raw Material Software ltd.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"#ifndef %%headerGuard%%\r\n"
"#define %%headerGuard%%\r\n"
"\r\n"
"//[Headers]     -- You can add your own extra header files here --\r\n"
"#include \"juce.h\"\r\n"
"//[/Headers]\r\n"
"\r\n"
"%%includeFilesH%%\r\n"
"\r\n"
"//==============================================================================\r\n"
"/**\r\n"
"                                                                    //[Comments]\r\n"
"    An auto-generated component, created by the Jucer.\r\n"
"\r\n"
"    Describe your class and how it works here!\r\n"
"                                                                    //[/Comments]\r\n"
"*/\r\n"
"%%classDeclaration%%\r\n"
"{\r\n"
"public:\r\n"
"    //==============================================================================\r\n"
"    %%className%% (%%constructorParams%%);\r\n"
"    ~%%className%%();\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    //[UserMethods]     -- You can add your own custom methods in this section.\r\n"
"    //[/UserMethods]\r\n"
"\r\n"
"    %%publicMemberDeclarations%%\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    juce_UseDebuggingNewOperator\r\n"
"\r\n"
"private:\r\n"
"    //[UserVariables]   -- You can add your own custom variables in this section.\r\n"
"    //[/UserVariables]\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    %%privateMemberDeclarations%%\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    // (prevent copy constructor and operator= being generated..)\r\n"
"    %%className%% (const %%className%%&);\r\n"
"    const %%className%%& operator= (const %%className%%&);\r\n"
"};\r\n"
"\r\n"
"\r\n"
"#endif   // %%headerGuard%%\r\n";

const char* BinaryData::jucer_ComponentTemplate_h = (const char*) temp_b930c59;

//================== jucer_MainConsoleAppTemplate.cpp ==================
static const unsigned char temp_a4c7812a[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"APPHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"int main (int argc, char* argv[])\r\n"
"{\r\n"
"    // This object makes sure that Juce is initialised and shut down correctly\r\n"
"    // for the scope of this function call. Make sure this declaration is the\r\n"
"    // first statement of this function.\r\n"
"    const ScopedJuceInitialiser_NonGUI juceSystemInitialiser;\r\n"
"\r\n"
"\r\n"
"    // ..your code goes here!\r\n"
"\r\n"
"\r\n"
"    return 0;\r\n"
"}\r\n";

const char* BinaryData::jucer_MainConsoleAppTemplate_cpp = (const char*) temp_a4c7812a;

//================== jucer_MainTemplate.cpp ==================
static const unsigned char temp_3f9400[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic startup code for a Juce application.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"APPHEADERS\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"class APPCLASSNAME  : public JUCEApplication\r\n"
"{\r\n"
"public:\r\n"
"    //==============================================================================\r\n"
"    APPCLASSNAME()MEMBERINITIALISERS\r\n"
"    {\r\n"
"        // Don't do anything in this constructor! It will be called before the\r\n"
"        // main Juce subsystem has been initialised!\r\n"
"    }\r\n"
"\r\n"
"    ~APPCLASSNAME()\r\n"
"    {\r\n"
"        // Don't do anything in this destructor! It will be called after the\r\n"
"        // main Juce subsystem has been shutdown and is no longer valid!\r\n"
"    }\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    void initialise (const String& commandLine)\r\n"
"    {\r\n"
"        // Do your application's initialisation code here..\r\n"
"        APPINITCODE\r\n"
"    }\r\n"
"\r\n"
"    void shutdown()\r\n"
"    {\r\n"
"        // Do your application's shutdown code here..\r\n"
"        APPSHUTDOWNCODE\r\n"
"    }\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    void systemRequestedQuit()\r\n"
"    {\r\n"
"        quit();\r\n"
"    }\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    const String getApplicationName()\r\n"
"    {\r\n"
"        return \"APPNAME\";\r\n"
"    }\r\n"
"\r\n"
"    const String getApplicationVersion()\r\n"
"    {\r\n"
"        return ProjectInfo::versionString;\r\n"
"    }\r\n"
"\r\n"
"    bool moreThanOneInstanceAllowed()\r\n"
"    {\r\n"
"        return ALLOWMORETHANONEINSTANCE;\r\n"
"    }\r\n"
"\r\n"
"    void anotherInstanceStarted (const String& commandLine)\r\n"
"    {\r\n"
"        ANOTHERINSTANCECODE\r\n"
"    }\r\n"
"\r\n"
"private:\r\n"
"    PRIVATEMEMBERS\r\n"
"};\r\n"
"\r\n"
"//==============================================================================\r\n"
"// This macro generates the main() routine that starts the app.\r\n"
"START_JUCE_APPLICATION(APPCLASSNAME)\r\n";

const char* BinaryData::jucer_MainTemplate_cpp = (const char*) temp_3f9400;

//================== jucer_NewCppFileTemplate.cpp ==================
static const unsigned char temp_28679746[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    FILENAME\r\n"
"    Created: DATE\r\n"
"    Author:  AUTHOR\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n";

const char* BinaryData::jucer_NewCppFileTemplate_cpp = (const char*) temp_28679746;

//================== jucer_NewCppFileTemplate.h ==================
static const unsigned char temp_dd2522cb[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    FILENAME\r\n"
"    Created: DATE\r\n"
"    Author:  AUTHOR\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"#ifndef HEADERGUARD\r\n"
"#define HEADERGUARD\r\n"
"\r\n"
"\r\n"
"\r\n"
"\r\n"
"\r\n"
"#endif  // HEADERGUARD\r\n";

const char* BinaryData::jucer_NewCppFileTemplate_h = (const char*) temp_dd2522cb;

//================== jucer_WindowTemplate.cpp ==================
static const unsigned char temp_817c51b7[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic outline for a simple desktop window.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"INCLUDES\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"WINDOWCLASS::WINDOWCLASS()\r\n"
"    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),\r\n"
"                      Colours::lightgrey,\r\n"
"                      DocumentWindow::allButtons)\r\n"
"{\r\n"
"    centreWithSize (500, 400);\r\n"
"    setVisible (true);\r\n"
"}\r\n"
"\r\n"
"WINDOWCLASS::~WINDOWCLASS()\r\n"
"{\r\n"
"}\r\n"
"\r\n"
"void WINDOWCLASS::closeButtonPressed()\r\n"
"{\r\n"
"    JUCEApplication::getInstance()->systemRequestedQuit();\r\n"
"}\r\n";

const char* BinaryData::jucer_WindowTemplate_cpp = (const char*) temp_817c51b7;

//================== jucer_WindowTemplate.h ==================
static const unsigned char temp_3857c57c[] =
"/*\r\n"
"  ==============================================================================\r\n"
"\r\n"
"    This file was auto-generated by the Jucer!\r\n"
"\r\n"
"    It contains the basic outline for a simple desktop window.\r\n"
"\r\n"
"  ==============================================================================\r\n"
"*/\r\n"
"\r\n"
"#ifndef HEADERGUARD\r\n"
"#define HEADERGUARD\r\n"
"\r\n"
"INCLUDES\r\n"
"\r\n"
"\r\n"
"//==============================================================================\r\n"
"class WINDOWCLASS   : public DocumentWindow\r\n"
"{\r\n"
"public:\r\n"
"    //==============================================================================\r\n"
"    WINDOWCLASS();\r\n"
"    ~WINDOWCLASS();\r\n"
"\r\n"
"    void closeButtonPressed();\r\n"
"\r\n"
"\r\n"
"    /* Note: Be careful when overriding DocumentWindow methods - the base class\r\n"
"       uses a lot of them, so by overriding you might break its functionality.\r\n"
"       It's best to do all your work in you content component instead, but if\r\n"
"       you really have to override any DocumentWindow methods, make sure your\r\n"
"       implementation calls the superclass's method.\r\n"
"    */\r\n"
"\r\n"
"    //==============================================================================\r\n"
"    juce_UseDebuggingNewOperator\r\n"
"\r\n"
"private:\r\n"
"    WINDOWCLASS (const WINDOWCLASS&);\r\n"
"    WINDOWCLASS& operator= (const WINDOWCLASS&);\r\n"
"};\r\n"
"\r\n"
"\r\n"
"#endif  // HEADERGUARD\r\n";

const char* BinaryData::jucer_WindowTemplate_h = (const char*) temp_3857c57c;

//================== juce_icon.png ==================
static const unsigned char temp_cf125308[] =
{ 137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,128,0,0,0,128,8,6,0,0,0,195,62,97,203,0,0,0,9,112,72,89,115,0,0,11,19,0,0,11,19,1,0,154,156,24,0,0,0,4,103,65,77,65,0,0,177,142,124,251,81,147,0,0,0,32,99,72,82,77,0,0,122,37,0,0,128,131,0,0,249,255,
0,0,128,233,0,0,117,48,0,0,234,96,0,0,58,152,0,0,23,111,146,95,197,70,0,0,76,232,73,68,65,84,120,218,98,252,255,255,63,3,35,35,35,195,16,4,140,88,216,76,72,124,70,36,113,70,52,113,108,102,192,192,127,52,246,127,52,241,255,104,226,255,112,232,27,18,0,
32,128,88,134,120,164,35,99,38,44,52,54,117,216,18,2,182,68,128,45,194,209,241,63,52,250,63,150,200,31,212,137,1,32,128,88,134,88,196,163,71,56,19,82,132,51,99,17,99,194,146,0,112,149,12,248,114,58,174,72,135,225,191,88,196,254,15,133,82,1,32,128,88,
134,80,196,51,97,137,120,102,52,140,44,198,136,150,24,144,205,64,174,46,208,19,0,122,177,254,15,45,242,97,252,191,80,252,15,137,141,44,246,15,45,177,12,202,132,0,16,64,44,67,40,226,209,35,152,5,137,70,102,51,179,50,51,177,176,48,252,103,102,97,102,102,
230,102,99,101,17,103,252,197,161,173,169,201,111,174,169,170,192,119,253,168,164,0,31,191,176,160,158,41,31,235,183,79,188,140,95,62,240,48,254,255,15,182,239,15,175,208,135,127,220,188,63,223,92,60,253,250,227,167,79,239,95,43,155,62,62,116,237,246,
253,219,183,111,127,251,202,196,246,251,211,175,223,191,254,252,251,255,239,207,127,134,191,191,255,254,251,3,141,108,100,26,93,236,47,150,18,98,80,37,4,128,0,98,28,100,141,64,92,17,207,140,22,241,172,232,180,32,7,43,187,0,59,43,7,47,39,7,71,156,185,
150,190,228,211,235,106,210,234,154,74,156,111,159,169,48,189,123,33,196,248,251,55,39,11,51,35,27,200,200,127,223,127,49,252,253,6,244,55,44,217,192,108,4,70,219,127,96,84,49,115,1,45,231,224,96,248,255,255,31,195,191,255,255,127,252,103,101,253,198,
32,169,244,225,227,127,230,187,111,63,127,121,116,237,55,219,249,109,183,159,221,122,253,237,231,183,15,191,255,253,120,255,253,215,79,160,238,223,208,136,255,141,196,254,131,165,116,64,46,85,6,60,33,0,4,208,96,73,0,232,17,207,132,37,183,195,34,28,134,
217,36,5,249,185,213,185,153,5,149,248,216,69,172,196,249,244,149,132,248,13,120,63,60,211,97,126,251,76,146,129,145,153,225,223,151,223,12,204,156,64,67,217,217,128,52,19,3,19,51,16,179,179,48,176,112,177,0,249,204,12,204,236,76,12,204,28,204,112,155,
255,124,253,195,0,202,215,127,191,253,1,226,223,12,127,127,2,249,191,255,49,252,253,245,159,225,223,215,95,12,255,129,114,140,32,245,127,255,50,48,42,170,191,124,245,139,225,210,51,86,158,75,123,174,223,63,253,232,47,235,187,43,47,223,191,7,38,134,239,
64,211,126,33,37,4,108,137,1,189,138,24,176,132,0,16,64,3,157,0,8,229,120,140,72,7,97,121,97,1,94,119,97,102,37,55,123,91,11,177,231,183,205,121,223,191,208,249,247,225,45,199,127,96,80,51,177,129,139,3,6,118,1,32,22,98,103,224,144,224,100,96,19,102,
103,96,7,98,102,54,38,6,86,46,102,6,70,78,86,164,22,5,35,82,109,15,141,131,191,255,25,254,127,255,195,240,27,152,32,254,254,252,199,240,243,253,79,134,159,175,129,248,205,15,134,159,239,126,130,249,191,223,127,7,39,22,70,86,70,6,70,110,222,175,95,228,
181,47,221,252,240,245,208,182,235,15,79,29,121,247,251,217,235,47,223,190,66,19,2,182,196,48,104,74,4,128,0,26,168,4,64,74,196,179,65,49,187,158,184,128,128,187,156,128,166,173,170,130,141,232,245,227,46,172,95,127,138,131,12,97,229,99,97,96,19,225,
100,224,16,230,96,224,146,226,98,224,81,225,99,224,18,227,96,96,224,102,129,154,206,8,142,84,48,254,7,165,225,65,141,20,222,200,225,192,204,8,193,224,178,136,9,218,12,252,199,240,255,219,95,134,111,79,191,49,124,121,240,133,225,251,139,31,12,63,94,127,
99,248,245,238,7,195,175,183,191,25,152,184,152,24,126,136,73,223,122,46,32,123,232,196,135,223,199,55,159,187,118,231,230,251,175,31,144,18,194,47,28,165,2,182,158,3,93,18,2,64,0,13,68,2,64,143,124,108,17,207,134,28,241,214,106,10,34,190,226,236,70,
58,28,255,237,196,126,125,179,96,120,250,68,132,149,155,137,129,75,154,155,129,91,153,159,129,91,142,155,129,83,156,19,152,227,129,202,217,153,33,65,247,251,47,52,104,255,163,6,37,41,94,69,209,199,8,209,203,2,36,216,160,29,136,31,127,129,165,193,47,134,
239,207,190,49,124,125,248,133,225,211,173,15,12,95,159,124,3,43,251,43,42,241,242,37,43,231,241,155,191,152,78,174,127,241,243,244,177,187,79,222,0,133,127,98,73,12,127,176,244,32,232,150,8,0,2,136,222,9,0,189,31,15,139,120,228,98,158,29,134,85,197,
132,248,147,141,148,204,76,57,25,188,249,238,95,179,96,250,245,141,131,133,135,153,129,83,146,151,65,80,79,152,129,79,155,159,129,141,159,13,18,41,160,92,13,172,175,193,17,254,143,196,136,38,21,252,135,86,29,32,31,176,50,65,216,127,255,49,124,7,150,12,
31,47,127,96,248,116,247,35,195,143,23,95,128,109,10,96,35,146,91,240,199,71,73,249,19,251,158,191,95,179,253,213,207,107,231,31,189,120,7,74,58,104,137,1,214,120,68,79,4,255,105,157,8,0,2,136,158,9,0,125,0,7,214,6,103,67,139,120,14,127,109,5,153,8,225,
127,62,82,2,188,70,172,15,238,169,114,252,255,46,36,100,32,196,192,171,38,8,204,229,28,12,172,192,186,157,77,128,21,146,43,127,254,67,212,221,140,180,114,246,127,112,241,143,232,197,129,74,3,102,212,225,3,80,34,0,37,6,160,91,126,125,252,5,172,22,126,
49,252,6,182,23,62,222,120,199,240,225,202,59,134,111,172,252,207,254,74,72,62,125,250,233,219,233,69,47,255,109,218,126,235,201,51,164,132,240,19,75,27,129,46,141,68,128,0,162,71,2,64,30,120,65,142,124,244,28,207,1,194,51,35,92,61,181,223,223,9,227,
120,241,68,253,207,135,223,108,130,186,188,12,18,78,210,12,220,10,60,144,22,59,44,204,255,64,235,114,70,28,86,162,12,237,252,39,207,217,255,128,153,243,247,39,136,126,70,86,136,24,40,162,255,253,131,200,49,177,64,251,140,160,222,37,19,68,29,72,158,5,
97,255,95,96,169,244,245,214,71,134,39,91,159,48,124,125,244,141,129,153,159,245,247,15,33,241,91,23,5,148,151,100,173,61,184,11,154,8,208,19,2,172,125,128,220,91,160,73,34,0,8,32,90,38,0,92,13,61,88,223,157,13,26,233,160,200,231,180,83,16,151,108,48,
145,41,228,125,112,215,252,255,199,15,252,172,192,6,156,168,133,40,131,168,141,56,3,155,32,59,180,104,255,143,39,8,96,173,121,96,248,253,254,2,84,251,23,90,230,0,173,99,1,245,5,217,160,74,136,12,195,63,95,33,17,43,97,203,192,32,160,206,192,192,163,0,
116,165,24,208,7,64,177,111,175,24,24,222,93,2,226,43,12,192,44,206,192,240,253,21,164,52,98,19,0,234,1,181,65,144,74,36,80,3,18,152,32,126,190,250,206,240,230,228,107,134,87,199,95,129,187,153,140,34,34,31,94,136,202,238,242,217,112,190,31,168,234,27,
90,66,64,175,22,104,214,83,0,8,32,90,37,0,92,13,61,22,164,198,29,7,20,115,89,41,203,136,215,75,253,41,19,126,255,214,250,255,239,63,204,130,58,2,12,18,14,146,12,156,242,60,144,94,26,161,136,7,141,222,252,1,70,250,95,96,216,177,242,50,48,8,233,3,109,224,
135,132,217,143,183,12,192,74,25,24,148,31,129,182,243,0,93,195,142,54,32,135,197,188,95,192,134,59,175,50,3,131,81,45,3,131,176,46,208,229,60,216,149,254,6,170,251,9,196,175,78,51,48,60,217,1,164,143,67,220,192,46,8,173,34,80,19,2,176,15,193,240,13,
216,123,120,177,255,5,195,135,203,239,24,24,185,88,126,190,16,83,216,157,114,226,89,223,139,207,223,128,14,100,248,142,163,52,160,89,3,17,32,128,104,145,0,144,35,159,25,173,200,103,67,42,238,57,65,184,222,207,222,194,237,221,149,2,246,247,111,229,88,
120,216,153,164,93,165,24,132,76,69,128,165,43,80,219,159,127,248,189,9,138,248,223,159,33,185,91,88,135,129,65,210,9,136,29,128,185,85,134,1,50,204,7,173,187,127,1,219,93,143,128,17,116,125,26,48,24,129,225,203,194,139,35,17,48,66,18,138,56,48,215,155,
180,66,114,252,203,135,12,255,79,109,5,234,191,193,240,255,229,35,160,235,57,25,24,197,229,25,24,84,140,24,24,141,93,128,9,69,8,90,98,124,131,148,10,55,231,3,19,194,81,72,73,4,178,7,61,33,48,3,19,2,208,95,111,79,190,98,120,182,235,25,195,239,95,255,255,
254,20,23,191,179,149,89,110,114,251,206,227,167,161,137,224,59,150,210,224,15,150,6,34,197,0,32,128,104,149,0,144,71,242,144,35,31,30,241,160,156,191,212,199,40,86,251,205,237,148,191,159,62,51,113,203,243,51,202,7,203,51,112,200,114,3,189,253,7,127,
38,5,73,130,114,26,51,59,36,210,149,35,129,185,94,23,26,233,160,224,3,38,138,15,175,33,197,47,168,200,22,145,130,232,121,118,144,129,225,108,53,36,135,131,19,1,90,255,16,148,152,68,76,24,24,108,103,129,139,255,255,7,87,51,252,235,74,0,22,208,191,161,
99,145,76,144,4,5,106,123,48,3,189,198,47,196,192,168,98,204,192,104,29,192,192,96,229,203,192,40,40,193,0,30,46,124,119,25,152,216,102,0,19,207,17,136,185,44,28,168,115,79,160,16,98,101,102,248,114,247,19,195,189,229,247,24,126,189,249,241,159,69,66,
232,235,5,22,145,249,169,7,238,172,252,243,239,223,87,164,106,1,91,105,64,181,68,0,16,64,212,78,0,140,104,131,58,44,232,185,158,135,149,153,71,73,86,70,184,89,133,35,93,246,249,77,127,6,22,102,6,62,101,1,6,89,127,89,6,54,73,96,186,248,242,7,127,255,235,
31,104,184,15,152,158,196,173,25,24,180,11,32,117,243,31,96,248,124,254,200,240,255,242,65,134,255,39,54,51,252,63,3,108,91,125,255,4,111,173,51,154,186,51,48,134,149,48,48,170,155,49,48,188,62,201,192,112,166,10,82,111,179,112,67,195,16,212,141,3,102,
58,46,105,6,6,199,101,144,34,255,248,38,134,191,237,209,192,196,2,204,128,220,60,136,158,6,220,41,255,33,141,193,159,223,33,209,34,36,200,192,232,155,201,192,20,152,15,116,19,176,45,192,10,244,246,155,19,192,132,48,155,129,225,61,176,173,240,23,218,104,
68,110,181,2,123,13,160,174,227,227,205,143,24,190,60,248,204,240,255,215,63,134,231,6,54,235,58,78,220,154,127,242,241,235,23,127,254,253,255,138,163,52,160,90,34,0,8,32,106,38,0,228,110,30,122,43,31,156,227,185,89,152,120,39,59,107,7,235,252,124,29,
195,252,230,165,56,151,20,15,131,148,167,44,3,159,6,47,52,231,254,67,157,164,133,7,246,63,72,206,2,181,184,165,93,129,57,62,12,216,48,211,6,230,176,39,12,255,15,0,35,236,232,6,134,127,143,129,141,177,183,239,33,234,185,128,214,50,179,32,34,234,51,48,
252,248,184,24,152,10,102,48,48,186,198,2,19,1,48,98,78,131,18,1,176,148,96,1,154,249,15,84,154,0,157,104,191,8,168,78,149,129,97,69,27,195,223,105,192,146,130,19,152,134,57,185,33,17,141,211,215,208,176,3,205,7,253,0,198,15,63,63,3,163,142,53,3,147,
123,18,3,131,177,27,48,241,0,253,246,233,14,3,195,229,94,160,189,167,160,61,10,22,68,136,177,49,131,19,215,135,203,31,24,94,238,125,202,240,229,241,23,134,255,138,202,79,231,63,248,220,56,237,250,171,11,208,146,0,185,145,72,213,68,0,16,64,212,74,0,232,
131,59,232,69,62,48,148,25,184,43,244,165,172,67,153,95,183,252,255,250,155,131,87,67,128,65,49,68,129,129,85,6,40,245,249,15,238,46,29,40,199,131,234,122,33,96,29,175,145,1,108,149,219,1,11,67,160,250,83,219,24,254,206,40,98,96,184,125,23,106,19,48,
80,217,216,17,195,182,40,67,188,160,32,252,194,192,40,42,205,192,212,182,147,129,65,17,152,120,174,77,98,96,184,49,27,52,237,7,12,214,55,64,179,83,25,24,12,128,137,226,225,53,134,191,73,218,16,115,184,120,240,71,62,70,215,243,63,164,68,248,250,23,28,
18,76,150,192,196,26,89,201,192,168,97,9,116,31,208,158,91,11,24,24,238,46,6,38,188,183,144,170,9,230,76,86,160,94,110,86,134,159,192,6,226,227,13,15,25,62,222,252,192,240,67,76,244,222,130,231,127,58,231,220,126,127,17,168,2,86,37,124,167,118,34,0,8,
32,106,36,0,244,200,103,65,234,219,115,65,49,79,166,142,148,97,20,239,183,10,206,79,31,101,133,141,69,25,228,252,229,24,152,120,128,233,228,235,31,44,185,158,17,146,235,65,93,49,54,62,6,6,133,16,6,6,157,92,112,11,254,255,131,171,12,255,119,45,100,248,
191,30,24,129,95,128,185,78,128,7,145,11,255,227,9,3,144,220,143,175,224,18,128,169,16,88,199,255,122,14,44,230,129,197,245,135,91,144,58,218,97,9,3,131,160,14,195,255,137,89,12,255,214,76,7,38,56,62,18,34,31,189,68,0,85,41,192,132,251,241,59,56,113,
50,250,103,48,48,69,0,19,151,184,44,176,90,0,150,2,103,234,129,254,126,140,84,5,65,1,176,235,251,247,211,47,134,199,235,31,49,188,187,240,154,225,135,128,200,195,121,175,24,218,230,222,122,67,179,68,0,16,64,76,84,206,249,200,117,62,172,177,199,157,102,
32,175,31,45,248,171,132,227,253,7,89,81,83,96,228,7,2,35,159,11,168,252,27,142,200,7,229,122,80,131,12,212,10,215,47,99,96,208,43,1,122,247,47,176,81,182,146,225,95,91,52,195,255,5,221,144,0,6,69,18,44,114,255,255,39,28,49,160,62,250,217,61,192,220,
15,172,2,120,20,25,24,68,205,33,137,76,200,0,88,116,3,187,125,95,129,237,8,96,117,194,0,74,152,255,201,44,85,255,67,123,30,32,187,64,238,3,54,22,255,175,156,193,240,111,66,22,48,247,3,75,116,17,96,59,196,164,5,232,55,113,200,120,5,114,177,7,108,255,48,
11,176,51,72,251,202,50,112,203,240,49,176,191,125,35,159,32,201,82,26,171,33,161,13,10,71,104,120,114,32,141,158,34,47,131,35,180,206,17,43,0,8,32,38,42,69,62,182,162,31,156,243,227,77,53,180,99,249,127,21,177,62,125,163,200,43,207,203,32,237,37,11,
158,147,103,248,241,15,211,185,160,72,2,245,231,65,117,50,168,174,183,232,99,96,144,15,98,248,127,251,28,195,191,73,192,156,217,17,7,236,102,1,51,131,16,48,44,56,184,73,207,161,172,192,18,228,221,11,134,127,39,54,65,248,18,86,64,49,160,57,98,230,224,
170,224,255,217,93,12,255,223,62,7,171,35,59,1,160,183,93,184,184,193,238,253,127,96,11,195,191,206,100,104,34,48,102,96,48,106,132,180,59,254,125,71,196,27,136,250,252,27,60,212,45,237,37,205,192,33,193,205,192,245,234,133,74,186,52,115,101,168,142,
130,58,52,17,112,65,19,2,59,210,160,26,19,3,230,58,71,162,0,64,0,81,171,4,64,238,234,193,235,124,31,107,83,133,120,254,159,185,108,143,158,171,114,73,115,2,27,124,50,12,204,160,41,218,95,127,49,157,9,170,231,65,117,49,168,88,212,202,97,96,48,111,7,246,
237,141,128,125,240,109,192,174,88,50,195,255,173,11,33,17,206,207,7,73,40,228,68,16,40,87,130,218,26,87,129,37,192,155,23,96,243,193,37,129,160,54,196,27,231,247,147,19,134,248,1,200,205,160,97,98,17,96,34,184,14,76,200,61,169,224,177,5,6,9,27,96,47,
6,232,207,223,223,33,126,71,182,19,88,50,242,104,10,128,171,73,54,97,78,6,142,39,79,85,178,100,216,10,28,117,84,101,145,18,0,108,20,149,5,169,36,32,217,225,0,1,196,68,133,220,207,130,54,180,11,78,0,110,38,250,114,197,242,28,57,60,183,239,235,115,203,
114,49,200,135,40,50,240,170,241,65,6,119,176,229,148,127,192,106,77,204,2,24,241,29,12,12,154,153,224,90,238,255,22,80,209,153,9,201,53,188,192,132,193,198,9,157,148,161,96,26,15,216,255,254,255,228,6,195,255,59,103,129,108,126,96,189,12,108,160,113,
75,64,226,234,230,105,160,29,108,212,201,253,24,211,135,140,224,246,202,255,235,103,24,254,245,167,131,27,165,12,138,126,192,94,135,50,164,212,67,142,59,144,23,191,253,101,224,213,226,103,144,3,141,141,136,115,50,240,220,187,101,88,163,35,84,32,43,42,
44,140,84,29,176,163,85,7,204,164,86,5,0,1,196,68,131,122,159,203,76,81,90,162,84,252,95,1,215,201,35,150,124,90,124,12,74,113,42,12,188,170,188,144,9,156,255,88,234,204,191,192,182,141,82,20,3,131,229,4,96,206,112,98,248,191,110,18,195,191,98,59,134,
127,51,129,245,63,176,200,6,247,195,25,25,169,51,248,197,6,76,163,31,223,51,252,63,183,27,152,251,128,237,8,5,127,160,249,178,12,255,159,221,3,230,204,7,136,238,35,173,0,15,176,36,56,179,147,225,223,212,60,96,180,9,49,48,168,197,65,198,8,192,109,57,164,
16,6,141,59,0,171,73,62,117,1,6,229,4,53,6,30,5,30,6,222,115,167,172,166,218,41,101,161,85,5,28,72,93,110,146,219,3,0,1,196,68,70,228,51,96,153,203,71,41,250,195,245,21,173,249,111,93,49,231,18,99,99,2,53,104,56,229,184,33,145,143,62,152,2,30,125,3,166,
126,25,79,6,6,221,2,96,252,242,0,115,124,58,48,226,171,25,254,223,187,0,105,232,177,178,81,55,2,64,221,59,80,14,187,117,1,146,184,4,52,129,98,64,167,63,190,14,204,117,159,161,179,122,180,156,27,101,4,15,39,255,63,178,142,225,255,93,96,123,70,198,17,88,
186,41,1,195,225,27,106,156,193,18,193,239,127,12,28,146,28,192,134,179,2,3,27,47,11,147,216,221,171,14,93,145,30,78,72,137,0,185,42,64,174,14,136,170,203,0,2,136,28,223,162,55,250,144,199,246,185,188,172,76,21,204,239,159,77,100,227,102,100,150,245,
149,103,224,81,6,22,251,223,255,224,142,124,73,123,6,6,227,102,96,11,252,39,176,145,23,197,240,127,195,60,160,201,192,220,192,206,77,187,220,8,52,246,255,171,187,12,255,223,63,131,204,35,128,192,155,39,216,171,39,90,0,80,91,228,231,119,134,255,59,230,
3,179,14,176,250,17,49,130,140,68,226,234,85,252,252,199,192,37,203,205,160,16,170,200,192,242,251,59,143,197,211,107,209,97,86,134,106,72,221,108,14,164,70,33,242,158,8,130,0,32,128,152,200,44,250,153,176,21,253,98,124,220,2,197,114,172,153,156,223,
191,139,138,217,75,51,240,25,3,139,184,159,127,177,148,220,208,161,87,94,96,3,204,162,23,40,207,202,240,111,235,76,96,255,126,19,120,64,4,60,206,78,43,0,10,80,80,43,31,212,218,7,69,58,76,248,221,43,160,175,232,184,30,19,88,18,253,191,115,30,18,22,66,
26,144,73,163,255,127,113,171,255,251,143,129,87,155,31,216,76,18,99,100,123,242,88,41,89,134,61,142,151,155,139,15,169,187,13,107,15,160,55,10,241,150,2,0,1,196,68,102,228,163,207,236,113,177,48,51,243,116,5,58,4,241,157,60,102,193,33,207,203,40,98,
42,2,212,192,136,88,128,137,234,27,200,92,187,73,51,164,213,15,236,126,49,44,1,246,141,121,25,105,95,7,131,0,40,129,129,18,230,147,187,144,117,3,32,240,241,53,3,93,1,40,52,127,253,128,132,15,151,4,98,65,9,158,118,36,19,80,147,144,129,48,176,42,96,98,
20,186,114,194,106,98,176,99,32,40,220,209,18,1,73,237,1,128,0,34,181,4,64,111,248,193,139,254,0,59,11,37,157,115,219,163,153,120,153,24,248,128,173,125,86,208,170,220,31,88,186,123,224,249,246,79,192,126,190,27,176,27,102,8,238,18,253,155,152,205,240,
255,203,55,72,177,255,159,14,185,144,17,210,14,248,255,236,54,176,222,255,4,17,3,45,222,101,26,136,229,241,36,12,224,1,171,81,78,96,85,32,110,37,14,26,62,96,81,191,127,214,59,211,197,194,0,71,215,144,133,152,174,33,64,0,49,145,144,251,209,39,122,224,
197,191,154,8,191,72,182,208,143,44,96,93,197,206,163,192,207,32,233,40,1,46,178,48,235,125,88,31,7,104,132,124,0,88,254,255,206,133,192,6,31,176,95,204,207,75,97,23,143,196,134,24,200,105,207,239,67,26,126,224,137,168,111,84,24,22,33,177,42,98,97,3,
175,15,96,248,241,158,129,168,149,172,160,82,128,133,137,65,196,90,156,65,64,155,143,129,237,241,11,105,95,97,230,32,3,21,69,113,180,4,64,116,85,0,16,64,164,84,1,204,216,38,122,128,69,16,119,151,155,65,28,223,229,179,250,160,212,169,16,34,199,192,204,
203,6,153,217,195,150,251,255,0,139,61,110,73,96,195,7,152,251,127,255,100,248,191,103,33,176,107,52,0,57,15,228,11,80,183,239,235,71,72,216,254,252,70,95,251,65,153,3,52,41,5,138,213,119,87,17,3,70,132,0,176,161,202,38,194,206,32,27,32,207,192,165,192,
201,32,112,248,144,85,165,149,90,144,152,160,0,63,218,80,49,11,218,80,49,86,0,16,64,164,148,0,232,131,62,224,220,159,19,224,174,39,127,227,184,15,104,173,188,184,173,4,3,155,60,47,142,49,126,100,91,217,33,141,30,96,253,251,31,148,3,153,153,232,187,31,
6,60,3,199,12,108,248,61,99,248,15,77,0,144,109,62,244,205,253,204,142,209,192,146,18,152,251,223,156,5,109,105,37,126,252,6,216,53,4,101,54,81,43,9,6,70,14,38,6,197,155,103,189,99,109,141,244,208,122,4,200,137,128,17,87,41,0,16,64,76,36,68,62,214,201,
30,255,191,79,34,255,126,251,197,196,173,192,203,32,108,44,194,192,240,233,55,129,6,24,208,163,223,159,67,134,125,217,57,24,24,117,108,25,24,190,252,165,115,253,251,31,226,142,47,192,158,200,231,119,116,46,122,128,254,252,1,180,87,203,156,129,65,31,232,
247,23,39,129,97,118,31,178,94,145,216,92,0,222,229,196,192,32,160,43,192,32,160,195,203,240,255,201,27,94,125,33,46,61,30,78,14,30,2,19,70,24,0,32,128,136,45,1,176,77,246,112,24,171,43,139,241,188,125,166,204,200,202,196,32,105,43,14,217,149,243,231,
31,158,132,12,93,12,1,26,250,124,186,27,220,31,102,242,207,2,58,25,180,210,246,59,237,7,97,176,181,3,96,9,128,46,123,35,160,51,157,160,0,13,175,4,218,255,139,129,225,209,22,232,10,102,180,81,92,240,34,152,127,72,237,34,52,247,253,254,203,192,42,204,193,
32,100,40,10,238,72,73,125,124,165,163,40,42,40,132,214,22,96,37,84,10,0,4,16,19,137,185,31,185,241,199,30,166,167,100,252,239,253,55,14,62,37,94,6,62,45,65,96,202,38,166,24,101,132,204,130,221,93,2,233,13,232,59,48,48,197,149,51,48,254,252,13,89,218,
69,175,68,192,8,169,118,254,127,122,139,40,153,104,93,13,129,74,185,143,63,24,24,93,163,25,24,141,157,33,43,146,222,92,0,134,40,15,116,129,43,48,60,126,0,197,126,190,133,132,13,12,131,196,126,127,66,77,8,255,33,37,1,191,150,0,3,175,26,55,3,239,173,43,
234,246,122,90,202,204,76,76,176,238,32,59,49,165,0,64,0,17,234,116,51,225,73,0,28,134,127,63,88,49,254,250,198,46,102,165,6,217,12,241,243,31,145,197,47,104,237,31,176,229,127,109,10,120,21,14,99,80,17,195,255,71,215,25,24,214,172,97,96,144,252,7,25,
175,167,117,119,16,148,227,65,206,125,15,237,255,179,178,50,208,52,5,128,34,255,21,48,18,213,53,24,152,146,219,33,98,247,128,254,253,120,11,50,37,205,12,244,51,143,60,3,3,159,34,176,108,87,131,172,108,6,137,129,102,11,223,94,130,44,61,255,8,236,182,178,
242,64,212,131,74,6,96,120,51,11,176,50,8,26,139,51,124,186,126,143,221,85,128,201,126,13,47,247,141,23,31,63,131,134,21,97,139,73,127,65,227,238,47,82,87,3,238,81,128,0,98,33,179,235,199,94,224,96,100,200,117,247,186,170,160,38,63,35,143,154,0,100,138,
151,164,58,24,216,94,121,176,22,104,146,48,3,131,102,58,3,83,106,63,195,191,95,255,192,99,228,12,223,127,67,102,255,192,203,187,254,211,56,1,188,132,112,217,56,104,151,230,64,161,248,246,51,3,163,130,60,3,83,201,108,96,15,72,154,129,225,254,74,6,134,
27,51,24,24,196,45,32,11,82,64,115,2,194,192,118,28,139,48,34,151,255,254,5,153,11,81,8,7,150,2,207,128,122,128,97,115,103,57,48,172,161,123,28,64,30,248,245,159,65,80,87,144,225,157,6,47,131,212,181,99,22,14,202,178,59,87,95,184,249,249,239,191,255,
63,144,74,128,95,208,76,12,219,95,0,79,4,0,1,196,66,194,192,15,188,1,200,198,194,194,225,206,253,219,155,227,245,87,126,9,71,53,240,34,93,134,63,68,134,4,124,217,2,51,36,21,223,154,11,12,156,51,192,146,160,154,129,169,28,200,246,207,96,248,55,191,134,
225,255,133,83,192,68,192,6,89,231,71,171,152,1,25,11,234,133,128,204,231,228,165,93,66,123,255,153,129,201,220,145,129,49,119,18,48,50,117,24,24,110,47,2,118,65,143,50,48,88,79,3,38,6,125,200,172,32,168,186,63,189,141,225,255,197,3,12,255,239,93,130,
12,80,253,249,5,89,213,44,163,194,192,24,215,196,192,168,153,3,89,12,123,44,23,50,131,10,42,73,129,109,1,102,126,54,6,126,13,65,134,207,183,31,177,199,232,242,249,109,190,202,122,231,235,207,95,223,144,18,0,8,255,70,138,83,120,110,5,8,32,66,37,0,122,
235,31,156,0,210,92,44,117,120,159,93,148,103,23,98,103,228,16,225,196,49,220,139,110,220,63,200,248,63,168,72,67,94,244,15,170,139,65,235,245,255,252,134,204,11,152,184,50,48,169,25,49,252,91,63,137,225,255,242,14,96,105,240,5,180,152,156,54,137,128,
17,218,253,3,37,68,80,3,154,218,3,81,160,18,236,3,48,34,197,196,16,145,15,170,250,64,107,0,20,67,32,43,146,95,62,98,248,183,174,153,225,255,201,173,64,246,83,232,178,119,38,104,12,48,66,6,203,110,159,5,102,136,131,192,210,99,46,120,137,59,131,70,26,3,
195,213,137,144,238,244,127,200,126,69,14,73,46,6,22,62,86,6,201,251,231,77,204,149,229,36,246,93,187,251,5,41,1,192,50,240,31,244,18,0,32,128,88,112,4,11,3,190,198,159,141,36,191,9,235,221,79,34,156,138,2,12,140,160,37,216,132,178,25,120,166,11,104,
156,32,176,136,19,183,66,172,136,5,1,208,214,173,247,87,33,107,231,119,251,3,27,133,229,12,12,114,190,12,76,241,141,12,12,230,62,12,127,123,147,129,69,223,101,96,34,224,162,254,72,29,248,92,160,223,144,86,56,55,63,245,115,254,87,96,233,194,199,11,137,
124,57,45,136,56,168,158,7,225,47,31,24,254,111,155,198,240,111,69,39,176,4,4,118,137,185,129,65,203,2,91,79,139,214,10,99,97,5,207,85,252,235,140,103,96,234,63,204,192,168,18,202,192,240,28,152,105,62,0,195,140,85,0,60,175,193,43,207,205,192,33,198,
197,240,229,198,71,150,24,123,93,43,96,2,120,132,150,0,144,27,130,240,68,0,16,64,44,68,54,254,224,137,192,92,77,81,92,252,237,35,45,160,17,140,188,202,188,12,76,44,140,56,134,124,25,32,107,249,255,254,133,212,115,160,84,43,98,138,40,122,209,123,11,63,
94,0,219,4,27,128,13,163,85,192,196,112,141,129,65,53,6,168,199,148,129,185,109,43,195,191,153,165,12,255,143,109,130,116,155,152,89,169,215,101,3,25,243,251,39,56,1,48,114,243,1,11,0,42,153,11,42,173,64,43,126,128,117,61,168,206,103,52,245,132,14,54,
1,195,226,243,123,134,255,91,103,51,252,223,56,153,225,255,243,231,144,136,23,224,197,29,134,240,178,154,21,162,119,239,98,6,198,132,38,96,130,242,130,236,64,2,149,90,191,25,25,152,4,217,24,64,241,241,245,193,71,6,181,23,87,44,129,189,129,245,127,255,
253,99,67,27,16,98,70,175,6,0,2,136,133,196,238,31,155,139,188,176,26,231,187,103,226,108,124,76,12,188,74,124,184,227,2,84,148,129,182,110,105,166,0,91,190,41,144,72,127,253,12,188,123,7,60,11,6,213,200,40,171,193,192,32,42,203,192,192,197,11,89,247,
15,194,31,128,9,224,205,121,96,238,249,0,148,211,100,96,170,89,193,240,255,248,102,134,127,139,129,165,194,93,96,105,193,244,15,50,107,72,105,151,17,60,35,247,29,82,10,128,118,243,80,101,136,23,24,174,63,127,130,19,47,83,222,84,6,70,117,104,162,255,244,
14,188,213,236,255,178,86,96,143,231,49,208,62,102,72,196,255,255,79,56,242,97,37,10,200,187,183,207,65,134,141,65,37,41,168,167,240,29,212,136,229,6,87,5,252,106,124,12,111,78,177,50,112,191,122,32,239,103,97,40,191,254,216,217,207,72,25,24,219,220,
192,127,128,0,98,33,162,248,71,169,255,85,24,191,169,49,191,124,38,192,163,35,192,192,34,196,129,189,231,4,174,199,128,218,180,243,24,24,148,163,128,69,225,39,200,10,152,85,221,12,255,239,92,195,28,147,23,145,1,7,20,163,29,176,94,4,209,66,114,208,34,
243,39,180,177,195,205,192,104,9,172,22,244,29,128,102,244,0,115,193,18,200,56,62,104,80,9,84,108,50,145,153,16,64,157,12,240,148,44,48,210,120,5,33,103,2,81,2,64,165,9,104,18,220,10,232,214,252,233,192,86,189,36,36,65,60,187,195,240,111,74,62,48,12,
118,66,134,104,132,121,17,37,5,73,9,150,153,225,255,67,96,248,129,150,175,73,201,65,26,132,224,253,5,60,224,106,0,180,104,132,93,148,139,225,27,176,20,112,226,251,98,176,30,216,196,102,192,92,51,200,140,212,100,103,4,8,32,22,28,197,63,250,228,15,184,
4,48,82,144,22,145,102,103,81,5,69,58,191,26,63,3,11,39,51,150,4,240,31,146,90,229,188,33,145,255,234,33,195,191,37,45,12,255,55,204,129,152,204,195,133,212,6,129,110,237,126,243,132,225,255,19,32,222,11,116,178,148,4,3,163,161,51,3,163,145,11,3,131,
172,38,3,35,104,99,167,24,100,123,54,35,176,148,96,76,0,150,2,206,209,12,255,87,180,49,252,63,123,136,225,255,135,39,144,163,97,64,99,7,132,230,212,177,249,20,20,105,160,165,103,124,34,144,46,215,255,255,36,86,49,140,144,72,6,38,36,70,113,96,164,184,
37,48,48,197,214,1,205,4,134,241,189,139,12,255,175,28,5,54,242,250,129,237,152,59,192,64,227,130,172,69,32,183,65,11,238,81,188,6,250,123,39,176,103,144,13,76,72,192,238,227,243,253,208,237,241,76,192,58,153,149,129,15,88,42,127,189,251,145,65,135,143,
213,152,155,131,125,211,215,31,63,145,207,84,68,223,71,240,31,32,128,88,136,40,254,225,85,128,179,146,132,42,255,139,59,138,108,2,204,12,220,138,192,226,31,52,184,129,190,140,10,20,24,92,192,148,175,145,14,172,179,62,49,252,155,86,200,240,127,39,48,98,
5,216,17,1,140,82,216,176,64,138,127,46,168,222,119,47,24,254,111,89,10,212,179,20,210,128,82,3,150,8,206,81,12,140,186,54,192,190,178,58,68,139,172,26,3,99,233,2,6,198,43,71,24,254,29,90,203,192,112,96,37,195,255,215,192,250,148,157,21,218,109,36,33,
1,252,252,1,73,0,160,220,10,90,117,252,227,43,241,9,0,164,14,84,130,252,250,205,192,168,109,193,192,148,210,14,30,217,252,255,244,54,195,255,77,192,18,224,240,122,32,251,1,36,36,249,120,200,203,245,232,246,253,249,9,172,70,129,13,65,127,96,2,16,2,150,
0,28,194,64,63,188,135,108,113,3,205,15,104,241,51,188,58,254,130,129,255,249,61,21,47,93,21,249,213,167,175,126,68,43,1,144,19,0,3,64,0,177,96,41,254,209,143,101,133,215,255,138,130,60,50,140,15,63,114,115,104,241,49,176,242,179,226,110,245,131,234,
38,78,73,134,255,123,128,17,121,8,216,120,227,101,65,139,124,44,141,38,88,151,16,156,24,254,67,138,229,239,95,25,254,159,218,199,240,255,252,62,112,66,96,176,13,0,86,5,126,12,140,138,58,16,245,58,54,12,76,64,204,0,236,26,253,219,60,11,220,143,102,248,
12,108,124,113,115,19,31,137,160,21,185,32,187,248,69,33,165,200,143,47,68,54,30,64,155,78,129,85,44,27,43,3,163,95,26,3,83,120,25,3,131,164,50,195,255,125,75,25,254,45,3,118,103,175,159,135,132,26,15,133,185,30,219,252,5,168,250,251,12,140,87,30,96,
162,101,23,133,12,41,131,98,10,88,13,112,74,114,2,227,134,131,225,219,243,111,76,118,202,188,90,171,129,46,65,235,9,160,180,3,0,2,136,5,199,224,15,70,9,32,201,207,195,35,254,251,179,44,72,148,83,156,11,114,94,15,186,167,64,45,82,144,35,37,44,25,254,127,
5,70,222,161,213,144,17,66,30,94,226,3,0,166,142,9,186,51,23,52,178,253,231,23,195,255,235,167,129,13,160,211,12,255,15,172,6,38,2,111,6,38,79,96,247,80,66,17,162,214,212,131,129,73,221,140,225,223,169,173,12,255,215,79,102,96,184,2,84,203,205,1,105,
57,227,179,23,150,131,127,3,115,48,104,32,8,188,39,128,136,57,4,80,162,121,15,212,167,164,194,192,20,85,206,192,232,145,8,113,239,182,57,12,255,38,20,3,35,2,216,247,23,228,66,28,23,67,205,49,12,80,12,125,120,7,44,250,129,237,0,85,77,96,248,0,19,192,7,
88,98,254,7,90,161,193,192,37,193,193,240,253,217,23,6,5,166,223,170,12,168,39,176,161,119,7,255,1,4,16,19,17,9,0,172,81,145,151,93,128,251,251,103,17,208,6,88,78,113,14,6,38,86,28,221,63,208,193,11,82,142,224,134,202,255,139,251,32,91,172,201,245,63,
44,240,64,93,63,62,94,72,17,125,247,2,195,255,229,237,224,131,27,254,239,95,129,24,188,225,19,98,96,114,137,101,96,42,95,200,192,96,231,15,108,28,253,128,12,34,225,42,9,64,110,2,173,67,0,45,4,1,13,78,1,213,49,242,8,225,95,152,9,106,108,254,254,1,222,
110,206,232,236,199,192,84,189,136,129,209,43,5,98,220,202,46,134,127,179,171,128,242,192,42,132,159,7,58,217,68,139,193,43,38,200,1,24,111,159,130,206,173,5,86,1,34,136,182,15,216,79,140,192,26,152,11,172,146,247,253,51,105,17,94,110,46,124,37,0,64,
0,49,17,104,3,192,27,130,202,210,18,66,252,255,126,137,177,112,49,130,143,96,69,108,195,70,11,85,208,106,31,78,57,134,255,55,142,131,135,64,25,216,217,169,51,201,242,31,122,42,7,104,203,54,11,59,176,113,5,172,255,39,100,51,252,171,242,2,150,52,171,16,
30,144,211,100,96,46,156,14,108,35,76,3,70,168,32,120,12,30,94,50,161,187,21,148,67,127,124,99,248,255,27,186,36,91,80,28,82,29,160,15,82,128,187,96,64,255,126,1,230,236,119,191,24,24,195,115,25,152,10,128,118,104,90,130,39,177,254,213,249,51,252,155,
95,207,240,255,27,232,108,33,78,218,206,42,2,221,2,114,239,255,247,47,32,124,80,27,128,1,169,148,1,102,74,208,241,184,160,41,122,30,198,191,66,190,6,234,138,104,221,64,148,68,0,16,64,76,120,34,31,165,26,16,99,103,22,100,126,245,84,136,13,216,152,3,47,
249,194,230,75,80,35,14,52,204,249,235,63,100,7,238,95,104,81,78,109,0,74,8,236,192,128,254,5,172,102,206,238,97,248,215,155,197,240,175,198,15,216,86,128,238,237,19,146,100,96,242,2,214,203,29,192,214,178,3,176,55,242,17,152,203,63,126,198,156,87,7,
23,231,255,33,231,13,128,19,128,24,226,116,49,228,200,7,53,20,95,126,2,87,73,76,37,61,192,198,94,39,176,209,40,197,240,111,59,176,200,175,3,218,123,106,59,244,148,48,118,218,79,41,131,236,1,245,92,160,147,88,224,147,201,96,231,33,49,66,214,9,112,138,
178,3,75,104,96,24,125,249,202,174,202,250,71,6,109,44,0,229,70,21,128,0,98,194,51,11,136,114,76,187,156,162,146,48,195,151,63,204,108,252,236,192,82,158,5,187,71,65,186,64,39,116,129,14,188,122,117,159,198,107,44,25,33,117,60,168,225,246,7,152,35,78,
111,7,70,70,0,195,191,246,24,134,255,87,143,65,18,158,186,9,3,83,229,18,6,166,166,165,192,86,186,17,164,129,8,106,241,35,15,32,129,252,1,93,15,200,40,38,135,178,67,11,50,114,247,25,28,177,76,1,177,12,204,125,7,24,24,67,139,193,185,239,111,107,20,195,
255,201,133,64,127,62,129,84,77,44,204,12,116,1,32,183,255,249,3,236,254,66,167,177,65,39,146,177,176,35,170,194,191,160,179,147,217,24,216,128,248,223,247,63,140,82,82,82,98,88,114,63,124,68,16,32,128,88,176,68,60,122,59,0,140,69,63,189,144,2,205,250,
177,9,115,0,237,99,198,82,255,255,135,28,209,6,58,86,237,219,23,72,17,197,74,143,0,97,68,228,190,127,127,192,103,8,252,63,190,137,129,81,82,137,129,49,2,216,64,115,140,4,98,96,55,210,200,21,60,185,244,111,105,31,48,39,3,19,1,7,23,162,85,253,17,186,40,
68,92,17,50,24,244,31,218,11,1,230,52,70,183,104,200,188,4,232,100,48,80,154,88,217,201,240,127,13,208,12,208,66,18,208,6,19,198,129,184,115,3,148,48,223,64,19,128,0,100,82,8,180,152,6,86,85,178,49,49,112,136,2,123,2,47,190,51,242,126,120,46,140,165,
10,128,119,5,1,2,136,9,71,238,199,72,4,44,207,238,243,50,130,142,91,231,102,129,52,0,177,109,242,4,173,77,226,146,129,172,252,5,77,103,50,209,51,80,160,245,52,43,7,120,168,244,255,195,43,12,255,154,163,24,254,21,219,131,187,145,160,227,220,24,211,186,
25,152,234,23,3,59,203,226,144,177,122,6,232,154,128,79,208,220,36,42,13,73,72,160,99,94,128,13,79,166,172,126,112,9,2,238,109,92,58,196,240,175,192,150,225,255,204,10,96,209,250,17,146,235,25,153,24,6,4,128,194,30,180,174,16,188,194,158,11,122,138,41,
210,9,232,76,140,224,19,212,255,51,252,99,100,124,243,148,19,91,227,15,86,23,2,4,16,190,70,32,74,2,224,226,229,231,248,247,253,31,3,51,55,51,142,85,188,255,32,39,114,130,122,1,63,126,128,251,240,144,110,208,0,4,16,40,103,179,114,130,119,21,255,191,0,
140,184,18,103,134,127,147,114,192,227,254,140,46,49,12,76,93,187,24,24,244,108,129,17,253,11,82,228,127,131,158,44,42,36,5,9,65,69,29,96,181,177,158,129,49,48,143,129,225,205,83,134,255,179,202,24,254,150,186,48,252,191,124,2,178,83,153,133,149,97,192,
0,172,49,11,170,182,64,109,19,80,152,51,49,99,38,0,110,54,96,135,134,9,40,205,203,138,165,68,135,183,3,0,2,136,9,207,80,48,74,66,224,22,145,226,130,196,49,43,246,173,218,224,57,117,97,232,152,248,87,136,3,153,153,24,6,28,128,78,233,98,231,96,248,191,
126,6,195,223,134,96,6,134,59,231,25,24,21,180,25,152,65,13,196,16,208,185,67,60,144,105,91,96,189,202,200,47,2,20,43,98,96,154,116,130,129,209,208,9,216,144,61,206,240,183,196,133,225,223,194,94,200,146,49,126,62,134,65,3,126,65,187,175,160,243,141,
64,243,46,104,93,78,22,80,70,101,98,96,228,22,22,97,71,107,216,35,199,45,3,64,0,177,96,201,253,200,227,1,240,226,130,237,251,39,46,208,104,35,19,43,19,142,235,22,255,66,150,119,129,152,160,34,244,23,168,158,165,82,23,144,226,238,35,208,155,188,192,162,
242,232,78,134,127,119,129,9,32,169,13,216,46,136,96,96,202,232,99,248,15,154,107,224,21,134,168,19,16,101,96,2,202,129,86,10,255,63,190,1,88,220,151,51,48,60,124,4,172,26,120,32,11,47,254,253,27,60,9,0,116,182,1,108,201,24,19,43,70,21,193,12,108,167,
49,49,255,103,96,250,254,133,141,1,251,245,121,224,120,6,8,32,124,211,193,200,235,2,24,25,255,254,102,6,149,52,76,176,226,31,219,24,0,27,116,81,197,151,15,208,69,63,131,232,70,82,80,125,45,200,203,240,255,245,43,134,255,45,41,12,140,87,79,50,48,69,150,
2,115,124,9,102,97,6,154,91,232,201,98,248,15,26,30,16,102,67,172,95,24,44,23,190,129,47,196,248,5,193,160,200,103,100,197,72,244,140,108,140,144,136,252,251,135,153,1,247,29,138,12,0,1,196,132,99,58,24,227,230,205,255,127,129,21,10,172,32,193,58,6,240,
31,114,228,10,116,238,27,178,254,116,176,36,0,104,236,129,119,33,129,186,123,192,198,222,157,75,208,237,217,12,24,171,229,25,117,108,24,24,147,27,25,24,157,220,128,165,26,48,247,127,250,2,105,116,49,12,162,68,13,26,11,97,134,174,243,68,31,189,4,141,113,
1,27,196,140,144,163,237,113,93,158,9,246,12,64,0,225,91,18,134,154,32,160,119,235,225,14,224,127,144,37,203,160,65,41,216,118,43,70,166,129,143,120,240,162,15,96,23,233,59,48,183,72,72,49,48,218,4,50,48,89,251,51,48,40,233,3,139,124,96,23,249,217,109,
96,143,225,6,176,155,232,12,140,108,46,134,255,123,151,129,207,243,99,140,171,99,96,4,246,100,254,159,220,198,240,127,223,114,134,255,103,119,51,48,124,0,77,52,209,120,161,42,177,13,65,94,1,72,213,245,243,14,228,160,106,92,9,19,18,111,140,56,170,121,
6,128,0,194,53,14,128,145,8,254,51,49,130,189,140,219,223,255,33,235,216,255,65,91,168,255,6,56,179,192,70,204,62,3,35,158,19,152,16,157,67,25,152,130,242,192,199,184,66,182,103,125,101,248,191,125,54,195,255,117,179,193,61,100,70,77,115,96,196,2,219,
185,243,170,192,71,190,50,154,58,49,48,133,150,128,219,10,140,230,94,224,4,240,15,52,247,112,100,61,176,68,248,12,89,182,206,200,68,255,132,0,179,15,20,249,160,54,214,167,15,144,99,245,208,23,197,252,255,7,235,17,252,199,87,116,1,4,16,161,101,225,112,
204,200,204,242,23,126,9,19,3,150,113,117,112,63,28,58,229,11,154,48,25,168,226,146,17,186,64,227,195,55,200,250,74,123,111,6,70,231,104,112,171,158,17,60,214,255,135,225,255,142,121,144,92,125,251,12,3,195,139,47,12,140,38,166,144,101,234,160,69,28,
160,217,193,119,47,193,83,217,255,110,3,27,140,174,113,12,140,158,201,12,140,182,193,12,76,6,142,12,255,237,67,25,254,47,107,103,96,184,124,1,88,26,48,65,102,44,25,24,232,151,16,254,67,59,111,130,144,147,205,24,126,188,131,28,129,207,136,122,26,249,63,
208,213,119,32,200,196,140,183,229,10,16,64,68,15,99,253,101,227,252,3,58,2,255,255,159,191,72,43,202,208,26,89,204,208,1,9,80,227,100,32,74,72,80,157,247,21,84,95,3,27,65,38,192,156,30,86,202,192,164,105,1,153,228,1,185,236,240,26,6,134,53,253,12,255,
238,92,6,207,35,128,71,242,64,137,4,212,183,7,5,42,120,107,26,208,12,78,118,112,215,234,255,147,91,12,255,23,214,51,48,2,19,11,163,123,60,3,163,111,22,3,163,125,24,3,3,208,76,208,250,3,134,45,211,25,254,191,2,70,0,15,27,100,210,139,30,137,224,63,100,
245,19,163,4,100,100,18,188,209,22,52,240,134,220,19,0,250,225,31,232,178,75,80,212,179,114,224,221,177,3,16,64,196,38,128,255,223,24,153,63,115,252,134,28,211,143,181,7,0,187,72,9,20,8,127,254,208,57,226,153,32,137,238,205,15,6,70,17,30,6,198,194,94,
200,25,254,160,58,30,228,186,215,143,25,254,47,110,2,230,234,85,144,250,18,212,117,130,13,5,131,67,129,3,98,198,207,175,208,201,32,38,232,240,50,7,100,11,251,227,235,12,255,231,84,131,231,251,153,252,51,25,24,253,114,24,152,226,235,25,24,220,227,24,254,
111,154,193,240,111,235,12,200,204,39,104,38,16,188,6,129,134,221,69,208,10,102,46,1,6,70,41,85,104,143,235,41,100,111,3,242,82,123,240,17,76,127,65,139,178,255,255,96,100,254,129,207,56,128,0,98,66,138,65,124,152,225,243,131,27,191,65,231,251,254,1,
93,158,240,15,219,186,57,70,164,121,233,63,244,41,1,224,197,253,39,240,74,92,38,255,120,6,166,41,167,24,24,61,146,192,145,15,58,123,224,223,210,22,134,127,5,54,192,98,127,1,80,253,31,72,78,69,174,47,65,51,197,224,190,52,19,176,219,247,13,58,29,140,28,
66,204,144,147,60,64,151,69,60,189,205,240,111,66,41,195,191,166,48,96,206,127,200,192,32,163,198,192,152,214,201,192,60,249,56,3,163,87,20,100,8,25,52,101,76,242,186,66,18,235,0,97,96,137,166,160,7,76,244,111,33,27,77,208,27,92,208,107,112,25,153,25,
25,190,63,125,240,7,41,142,49,0,64,0,177,16,89,235,48,252,230,21,250,198,240,237,61,208,224,223,12,255,127,255,3,27,142,181,175,77,175,250,16,52,171,247,227,39,120,249,23,147,83,32,3,99,88,25,184,104,6,131,63,64,55,110,159,7,142,124,134,167,247,129,69,
58,7,100,250,24,91,24,128,15,139,96,135,46,180,248,130,56,52,10,91,147,8,164,14,148,193,15,173,6,159,43,12,110,32,250,102,48,48,42,27,48,48,149,47,98,248,15,76,120,255,103,149,130,79,52,7,223,29,192,12,93,163,72,237,6,32,232,100,17,113,25,200,189,7,160,
4,0,191,136,226,63,164,243,254,231,31,195,239,47,191,193,252,63,92,188,160,229,75,56,35,4,32,128,88,176,4,7,86,252,89,66,233,221,255,199,119,24,126,125,248,9,172,6,254,51,176,112,35,175,192,133,174,238,253,250,140,129,65,10,116,254,143,54,100,238,233,
255,63,234,119,5,65,21,27,168,174,150,80,4,47,140,100,50,247,97,96,144,86,1,7,206,255,55,192,226,112,55,48,34,118,1,241,163,27,144,225,91,30,30,124,25,0,26,10,208,107,223,64,221,87,80,67,144,80,238,5,45,31,3,29,111,179,97,38,195,127,160,125,140,106,38,
224,158,2,99,112,1,3,227,244,115,12,12,247,175,128,79,34,253,183,127,57,3,195,237,139,208,129,88,42,108,104,1,133,39,143,32,48,193,199,64,252,243,108,63,164,13,128,124,253,13,120,225,40,232,252,13,80,201,207,252,255,151,152,60,48,85,63,194,25,183,0,1,
196,66,32,231,195,241,163,79,223,95,27,254,103,252,255,235,195,47,198,63,63,255,0,237,68,155,255,6,77,139,130,46,77,2,49,21,245,24,254,179,51,65,2,147,133,74,39,125,130,138,102,240,138,99,62,96,139,60,136,129,49,177,5,114,121,19,8,0,35,30,212,69,251,
191,182,143,129,225,49,48,17,114,49,66,22,134,254,39,98,153,56,184,4,96,133,84,11,160,129,34,80,201,66,240,168,58,232,240,50,104,153,26,168,87,113,241,48,195,255,83,135,25,24,14,174,98,96,74,106,103,96,212,182,4,38,134,66,6,230,160,66,134,127,7,129,238,
2,182,29,24,174,30,135,108,64,1,15,167,50,145,151,24,64,183,150,171,26,50,48,152,121,0,187,127,183,32,219,195,254,51,96,44,135,255,15,140,31,208,37,215,12,204,204,255,95,253,252,247,14,91,149,14,3,0,1,196,66,40,226,97,248,249,221,155,223,152,196,4,127,
253,254,252,133,253,47,232,146,7,17,180,162,13,148,194,63,221,3,223,150,5,94,138,197,47,12,153,103,167,244,232,117,80,34,2,69,10,27,47,3,163,1,48,96,65,125,115,208,68,13,184,97,242,14,178,155,118,97,3,195,255,171,151,33,75,203,133,121,160,37,18,9,199,
175,177,113,65,26,176,160,241,11,240,168,26,43,241,69,50,40,66,65,139,94,185,129,236,27,231,25,254,149,122,48,48,154,185,128,103,18,25,53,204,24,152,28,34,24,254,131,240,178,54,134,255,199,54,2,51,227,77,200,68,14,248,160,12,102,226,87,76,253,131,158,
22,98,236,10,241,215,203,227,160,134,25,228,172,0,100,127,130,238,40,124,241,11,88,74,255,101,96,230,229,252,247,244,249,211,15,12,152,87,209,194,3,7,32,128,88,8,68,60,252,230,202,23,12,236,31,191,137,72,189,99,184,117,65,242,247,7,96,181,34,199,141,
86,2,128,46,128,120,6,217,176,200,35,5,217,238,245,250,53,100,85,47,57,141,59,80,196,131,234,120,14,14,240,218,59,70,159,116,240,84,46,220,177,55,79,51,252,95,217,203,240,127,255,74,200,148,174,16,242,121,2,36,172,64,6,101,68,80,143,0,164,23,180,77,12,
84,210,176,50,146,87,55,243,242,66,86,235,28,219,3,44,17,246,0,19,172,45,216,205,224,75,171,162,170,24,24,194,203,129,238,93,202,240,255,40,48,33,220,56,11,62,164,10,188,113,150,25,186,195,9,20,134,176,5,46,48,115,193,139,83,126,131,47,175,98,52,112,
96,96,116,3,54,112,191,220,97,96,184,187,12,218,240,102,97,64,153,10,102,101,102,248,254,250,7,48,1,252,97,248,195,199,243,227,220,15,222,39,12,168,55,144,162,36,6,128,0,194,87,2,160,104,122,240,233,199,167,247,12,76,111,57,126,49,72,254,4,90,0,190,106,
134,137,1,245,122,55,208,128,196,211,189,12,12,234,197,12,140,58,118,192,220,121,14,218,37,98,36,46,210,161,13,56,240,122,2,144,223,100,180,129,245,124,42,3,163,107,60,100,232,19,60,240,241,5,28,128,255,22,53,3,3,17,152,155,132,160,203,194,254,145,185,
252,26,100,45,59,52,1,252,248,6,221,55,75,230,125,4,176,133,171,66,188,224,110,233,255,179,192,170,225,244,97,96,137,101,1,44,185,10,25,24,181,128,9,217,37,14,140,25,174,30,1,202,237,4,175,105,4,159,84,254,245,29,100,16,10,189,185,2,98,115,177,65,134,
176,211,187,33,213,206,137,70,200,105,33,28,162,12,24,119,35,1,193,183,231,223,129,5,217,127,134,143,28,188,111,142,29,185,241,26,45,62,81,50,57,64,0,161,151,0,255,176,69,62,8,63,126,255,233,235,27,38,214,183,146,140,160,27,215,190,129,79,243,96,6,223,
120,245,15,181,29,240,236,0,248,2,38,38,96,164,253,221,179,20,88,63,3,237,23,68,46,150,209,198,233,97,197,60,200,243,63,255,131,75,95,70,121,45,6,6,27,63,6,38,251,16,6,6,21,99,132,150,187,23,24,254,109,154,14,108,228,45,128,140,237,139,243,66,93,75,65,
21,3,74,196,28,208,210,12,84,2,80,163,3,3,94,29,5,244,8,232,58,251,223,192,30,201,165,19,192,158,65,18,248,218,58,70,75,31,240,62,71,6,109,27,96,91,1,136,221,19,193,7,66,252,127,122,7,178,231,239,37,176,215,242,238,53,36,17,130,110,27,17,7,54,118,245,
128,37,137,67,20,164,55,115,23,24,166,15,55,66,214,2,98,75,204,160,91,204,159,129,174,176,103,252,255,156,93,224,233,207,223,191,209,111,30,69,73,8,0,1,196,194,128,61,205,33,151,2,96,205,159,191,255,252,117,247,203,159,103,186,28,236,255,190,63,255,202,
244,23,216,29,4,205,57,99,12,200,124,125,2,217,226,173,6,76,4,192,98,239,31,104,9,213,91,96,67,20,116,71,16,120,137,56,180,187,2,202,233,160,57,237,159,208,42,87,72,148,129,81,197,16,178,201,3,88,212,49,128,216,48,0,90,149,115,100,45,195,255,45,179,25,
254,223,185,2,185,106,141,143,151,242,238,230,63,232,53,117,176,179,1,126,253,160,114,143,5,218,88,4,237,2,6,157,14,126,102,63,195,255,11,251,25,24,129,25,131,209,23,88,165,217,5,51,48,128,214,46,130,48,76,15,232,232,186,47,208,157,30,160,132,41,0,93,
132,242,253,49,48,242,129,13,205,235,211,33,155,65,25,209,206,52,2,49,129,225,242,247,227,47,134,31,175,190,51,48,114,176,48,156,127,247,227,46,82,228,99,77,4,0,1,196,66,32,226,255,33,107,190,240,244,245,51,103,1,190,55,204,47,222,136,125,7,22,51,224,
75,157,81,134,132,161,99,196,247,65,155,60,157,129,197,119,14,3,147,152,52,195,191,221,75,24,24,46,236,3,22,91,72,219,174,64,9,66,66,14,216,80,2,246,221,141,128,141,38,121,29,6,70,41,101,96,66,16,67,205,76,160,113,251,237,243,25,254,223,61,7,57,206,149,
135,154,103,7,65,219,0,176,4,0,26,200,161,197,248,13,120,161,38,39,100,171,24,176,62,255,127,235,28,195,255,25,192,106,242,240,58,6,166,152,106,6,6,208,89,137,32,183,188,2,70,240,59,96,183,145,91,10,178,208,243,61,176,91,250,20,152,161,62,191,0,150,235,
192,46,238,231,135,208,171,111,185,176,183,115,128,61,175,207,231,63,51,252,254,242,139,225,39,39,207,231,245,87,30,220,129,198,29,206,59,136,1,2,8,219,56,0,114,10,129,105,0,223,93,123,232,225,171,231,201,154,122,207,120,94,190,22,251,114,239,51,3,175,
58,63,3,19,122,125,9,26,148,0,53,6,207,0,235,41,227,122,6,70,251,80,6,102,125,71,200,53,45,160,179,111,62,191,101,96,228,23,103,96,144,85,103,96,4,13,213,10,203,64,183,142,125,133,180,108,127,232,0,83,62,100,162,227,255,218,9,12,255,150,181,2,27,150,
111,32,3,42,92,208,254,46,181,6,154,96,243,90,28,92,16,254,239,31,52,156,191,130,186,25,84,34,128,150,169,129,182,187,157,222,197,240,247,217,93,96,215,17,216,165,117,8,7,182,115,212,25,24,158,0,51,202,213,25,144,243,127,192,179,236,191,145,246,78,178,
64,102,92,177,69,62,19,100,167,214,199,91,159,24,254,125,255,203,240,66,89,235,238,163,227,199,63,51,32,238,29,254,131,165,4,248,7,16,64,132,74,128,191,200,6,124,249,254,227,231,125,6,174,39,178,156,44,122,159,238,126,100,18,253,44,206,192,198,207,134,
101,72,152,21,146,146,143,23,0,139,114,96,221,165,24,12,140,108,27,240,66,11,176,201,200,99,67,95,129,117,222,237,53,144,83,65,84,98,33,145,255,254,37,195,191,217,192,22,51,104,231,47,232,160,36,46,34,6,115,40,137,20,80,35,18,196,251,243,155,94,115,186,
144,54,2,40,49,188,124,192,240,111,50,176,203,248,233,45,3,147,95,22,176,52,40,132,228,242,71,155,33,179,171,76,108,104,51,171,56,70,51,217,24,25,126,191,249,1,172,129,191,128,59,19,167,191,179,220,96,64,92,65,143,158,8,96,87,210,255,7,8,32,124,37,192,
95,36,3,224,134,156,126,253,229,161,169,144,216,59,166,199,207,69,126,190,248,193,192,198,135,101,221,31,168,84,0,141,11,128,218,3,151,122,25,24,238,0,171,0,126,117,200,217,56,160,226,11,116,87,31,168,148,248,246,28,88,34,0,19,192,79,96,81,103,84,15,
44,254,245,192,183,116,255,235,75,129,172,192,101,103,163,254,149,49,216,0,204,142,191,127,232,59,131,13,155,112,250,242,158,225,63,232,24,156,111,159,193,123,25,24,244,75,33,103,38,129,194,143,88,7,1,219,99,95,239,127,97,248,245,254,59,195,95,110,174,
159,203,206,221,184,134,20,233,216,170,0,112,53,0,16,64,184,18,0,122,238,135,37,130,223,91,207,94,121,16,225,166,253,138,227,217,51,145,79,183,62,50,112,171,242,65,142,249,197,118,43,8,19,180,143,250,13,88,135,125,125,138,180,116,9,54,113,4,42,182,126,
65,174,137,83,12,4,159,134,245,175,3,216,229,187,15,116,59,23,23,29,150,148,65,219,0,204,172,136,161,214,129,0,160,68,0,236,129,252,91,80,203,192,4,108,248,49,6,228,64,74,78,80,230,33,102,98,137,25,114,78,195,135,155,159,25,254,126,249,199,240,66,75,
243,206,195,211,224,227,97,64,113,246,11,45,19,163,220,52,10,16,64,76,120,198,0,254,162,21,29,96,131,64,213,192,117,6,174,59,255,217,217,126,127,123,242,149,225,31,214,43,97,176,204,18,130,230,171,65,245,23,24,179,67,248,160,200,7,121,84,51,131,129,225,
193,117,134,127,45,209,192,210,226,42,105,251,251,41,110,165,51,161,78,165,14,8,248,15,153,172,2,150,64,255,102,20,1,171,190,117,144,91,212,36,29,193,35,171,4,107,49,96,238,255,9,108,148,127,125,248,17,92,189,30,254,201,121,17,91,233,141,165,29,192,0,
16,64,76,68,180,1,96,169,8,134,127,111,187,247,250,198,23,17,233,183,223,95,126,97,248,7,154,117,34,231,164,111,208,8,152,4,176,245,171,95,5,44,238,94,49,252,91,209,206,192,112,243,38,228,226,8,250,148,191,144,28,207,206,197,192,200,54,208,9,0,218,83,
0,53,114,129,225,9,58,75,137,1,116,135,145,78,54,228,238,100,134,127,248,7,178,88,24,25,190,62,250,202,240,235,237,119,134,31,66,130,31,151,158,189,121,13,185,212,102,64,189,103,24,165,4,0,8,32,38,28,105,10,150,66,254,96,73,0,191,142,92,190,241,226,154,
128,216,213,239,223,88,254,188,187,244,142,225,63,51,137,103,234,128,14,126,226,85,99,96,48,239,129,156,2,178,160,134,129,97,235,82,6,6,17,78,250,173,36,2,183,176,255,66,150,116,65,27,129,144,197,28,3,152,8,64,37,18,47,27,195,255,107,39,128,61,166,243,
192,146,80,17,216,91,242,134,174,194,193,53,144,5,41,254,191,60,248,4,94,23,178,151,79,253,192,235,119,239,191,225,40,254,255,160,13,4,49,0,4,16,182,4,240,15,75,21,128,145,8,22,220,124,115,230,171,136,212,187,87,39,94,130,7,31,136,62,97,11,148,235,64,
39,108,232,230,65,246,18,158,216,196,240,111,249,108,134,255,220,176,13,14,116,140,1,208,214,112,208,96,11,116,171,23,35,203,32,168,10,64,147,103,160,1,201,19,91,129,141,99,96,176,75,58,224,14,23,104,241,255,227,201,55,134,79,215,222,49,124,23,17,127,
183,232,234,227,203,191,255,252,249,133,37,247,99,45,1,0,2,136,9,123,191,8,165,26,64,54,8,118,250,244,175,115,183,238,190,121,40,42,125,231,251,187,63,127,223,95,0,205,250,17,121,245,0,168,7,32,8,236,235,139,219,128,199,222,255,174,232,128,172,218,101,
231,160,127,35,236,31,108,34,8,58,162,9,154,19,24,12,155,63,64,109,103,208,152,201,143,79,192,158,147,28,116,185,61,142,190,63,208,193,239,206,191,101,248,241,234,15,195,9,1,213,51,47,223,190,251,130,150,97,113,54,0,65,70,0,4,16,190,42,224,47,90,87,16,
150,0,224,137,96,231,243,47,87,128,13,182,223,47,79,188,134,148,2,44,140,4,2,240,63,244,102,112,55,200,204,23,232,208,200,107,64,143,242,114,12,204,182,43,144,149,160,197,29,176,249,127,142,65,146,0,192,71,216,254,132,14,85,195,246,118,98,113,24,7,19,
195,207,103,223,25,222,159,127,205,240,83,84,232,243,166,187,47,174,125,249,246,253,39,129,214,255,63,100,195,0,2,136,9,79,219,18,87,67,16,158,8,246,93,187,247,248,15,31,247,183,159,175,190,51,188,57,5,186,2,134,133,64,183,245,31,100,96,3,124,91,55,3,
228,128,228,127,12,72,199,20,208,25,128,214,127,130,18,0,172,4,0,29,24,61,24,54,254,128,66,28,116,164,60,248,216,186,55,208,101,223,140,88,71,254,222,95,4,22,253,207,127,49,60,20,81,184,115,251,233,203,15,216,26,237,88,122,0,240,18,0,32,128,112,149,0,
48,140,62,24,132,92,13,252,124,253,241,243,151,107,60,210,87,64,70,190,58,254,154,225,55,48,33,224,61,20,234,63,52,69,243,200,66,184,143,111,65,207,70,30,160,108,7,178,150,79,24,177,221,27,52,39,192,204,52,176,187,126,96,213,160,190,3,164,129,10,26,33,
5,237,182,70,63,108,1,88,247,127,3,214,253,111,129,185,31,52,188,114,243,31,251,163,55,95,190,126,69,111,171,225,43,254,65,0,32,128,152,8,20,144,232,35,130,176,220,255,3,102,65,239,149,215,7,191,203,201,189,249,245,238,59,195,243,253,207,33,41,149,133,
17,255,224,59,35,52,199,129,143,107,25,192,110,23,104,101,150,140,42,228,194,74,16,0,237,31,96,101,31,184,1,33,70,232,133,82,188,236,12,76,154,86,144,92,254,116,31,34,188,224,35,151,204,12,255,126,252,97,120,115,252,37,195,215,7,63,24,62,26,26,61,222,
117,255,213,237,63,127,255,253,68,175,166,113,36,0,56,0,8,32,38,252,131,228,24,9,224,23,90,34,248,113,243,225,227,247,147,126,73,173,251,199,206,244,251,221,249,55,12,175,246,128,214,228,225,57,132,28,180,100,28,52,42,8,242,47,104,246,239,215,0,37,0,
208,184,63,59,48,128,85,76,192,71,170,128,221,3,58,9,132,157,99,0,187,129,192,224,254,252,143,129,209,37,26,178,119,241,201,78,6,134,215,167,16,35,149,208,162,255,63,48,129,190,57,246,10,136,129,141,63,9,145,143,11,158,253,220,119,230,246,253,87,216,
170,105,164,4,240,15,91,2,0,8,32,38,2,5,36,182,222,0,44,242,225,169,109,245,161,19,247,142,41,88,30,249,251,254,15,195,75,160,195,190,222,4,86,69,60,88,14,146,2,165,228,63,192,20,254,241,38,132,175,101,137,119,140,131,166,57,13,180,145,68,76,6,216,205,
2,70,250,151,251,64,119,125,2,31,90,13,190,156,226,239,223,129,113,211,135,175,12,140,70,38,12,76,81,181,192,112,249,0,153,251,7,101,24,228,98,18,152,0,190,222,251,194,240,98,239,51,134,127,64,119,158,150,208,56,179,250,252,205,59,208,220,255,3,41,110,
144,27,129,40,19,64,200,137,0,32,128,8,245,221,208,135,133,145,83,216,119,100,11,27,247,94,56,252,73,78,238,37,168,42,120,117,248,53,80,244,31,100,51,5,198,252,0,80,236,237,5,176,209,140,22,190,192,92,39,2,89,138,69,239,173,228,63,129,246,131,54,118,
8,74,67,86,49,253,124,7,94,151,199,40,174,0,25,120,161,171,123,128,118,125,249,204,192,40,39,207,192,148,209,195,192,32,5,116,195,165,126,160,216,3,212,69,163,224,94,244,111,112,85,251,243,253,111,134,167,10,42,119,103,159,189,123,254,215,239,63,223,
209,75,102,164,68,128,49,252,139,12,0,2,136,152,18,224,63,218,160,208,47,36,75,224,137,224,61,176,1,50,245,51,247,150,255,140,12,127,191,62,252,196,240,245,225,23,72,255,254,63,250,64,7,176,161,245,28,88,175,125,186,11,62,161,155,209,43,21,200,166,115,
142,251,15,189,219,80,197,8,88,239,11,50,48,188,60,5,89,108,1,10,99,208,158,134,159,116,206,253,160,3,170,5,161,215,202,232,217,51,48,188,57,3,116,211,49,6,140,187,159,129,185,255,203,205,79,12,31,174,188,103,248,46,194,255,113,249,243,223,71,110,62,
121,254,22,41,67,126,71,43,157,127,163,13,254,96,180,184,1,2,136,152,209,155,127,104,213,192,47,180,148,6,79,4,91,46,221,126,176,87,193,122,255,183,23,191,255,191,60,248,130,225,255,231,63,224,85,42,168,137,157,5,178,63,239,206,98,72,123,16,116,16,147,
150,6,100,203,53,189,114,29,116,229,47,163,154,25,132,15,90,109,3,171,150,148,244,232,219,41,1,45,67,19,148,96,96,202,155,4,62,8,27,60,115,122,5,152,16,126,190,65,205,253,160,189,171,191,254,50,188,58,243,154,225,47,19,211,239,19,34,154,103,86,94,121,
120,7,41,14,190,163,37,2,244,250,31,235,114,105,128,0,34,166,10,192,214,37,252,133,102,49,56,1,252,4,22,69,29,251,207,158,120,97,96,124,231,237,169,183,12,79,119,62,5,102,182,255,104,163,132,255,33,167,91,130,174,140,123,121,152,129,65,8,232,249,220,
41,144,165,94,223,191,51,208,188,91,0,59,249,83,92,22,124,236,60,195,255,47,144,203,25,65,221,45,144,23,181,45,192,3,44,224,181,1,180,46,133,64,75,208,128,213,16,115,221,42,6,70,251,112,200,54,175,51,85,192,18,224,20,100,73,24,44,44,128,57,255,31,176,
104,125,177,227,25,195,135,171,31,255,63,82,215,191,85,185,237,228,17,164,56,248,6,197,176,248,192,86,252,99,77,214,0,1,68,236,190,45,124,165,192,119,36,203,127,124,248,246,227,203,148,7,223,247,253,228,21,252,242,250,200,51,134,215,135,94,50,252,5,37,
2,148,246,0,244,232,161,243,45,64,79,63,98,96,52,112,102,96,138,169,7,154,204,138,116,182,0,13,187,127,160,117,31,26,230,12,140,160,6,224,135,123,144,238,40,104,1,6,176,191,205,168,160,11,94,174,6,62,85,132,86,137,17,212,3,1,217,169,98,204,192,84,182,
144,129,1,116,104,5,168,216,7,69,254,139,67,144,161,95,88,105,200,12,172,83,129,110,126,123,236,37,195,139,131,207,25,62,136,136,189,234,187,252,106,223,191,255,255,145,115,252,55,36,252,3,169,248,71,111,253,99,36,2,128,0,34,38,1,252,199,209,24,252,137,
197,1,224,68,176,247,252,213,199,171,69,20,119,253,226,18,250,254,120,227,67,134,151,59,129,45,86,208,197,18,172,72,155,145,65,107,222,64,43,130,142,101,3,235,223,155,12,140,161,165,12,76,9,133,144,11,37,191,127,167,93,2,0,157,26,194,203,13,94,103,15,
94,155,7,218,95,7,242,18,104,87,211,171,83,224,97,97,102,207,36,160,27,64,237,4,42,215,5,160,56,253,9,57,204,129,209,61,137,129,185,113,29,3,163,186,33,3,195,85,96,145,127,36,29,216,229,59,13,172,50,133,160,221,101,6,112,120,129,242,206,11,96,248,61,
222,244,136,225,183,160,208,215,165,44,210,123,78,222,127,250,28,41,220,191,66,241,55,44,197,63,114,235,31,43,0,8,32,82,118,110,254,199,49,38,128,145,8,128,169,243,199,164,253,231,46,236,21,80,58,242,139,137,237,247,243,61,79,24,94,29,120,193,240,239,
23,242,45,225,208,147,69,65,27,28,142,131,206,216,7,150,4,9,173,12,76,169,205,224,13,144,12,95,190,208,96,68,142,17,60,195,6,218,205,11,222,94,246,7,216,238,120,117,2,186,234,6,88,223,62,222,2,81,102,27,194,192,32,192,3,185,252,137,42,165,0,116,225,44,
232,176,41,30,33,6,166,228,54,6,166,130,25,144,147,73,47,118,2,91,252,61,144,238,49,155,32,34,164,217,32,145,255,114,207,51,134,23,251,159,49,252,97,99,249,189,139,87,254,240,162,163,231,111,64,35,25,61,242,209,115,255,95,92,163,127,200,0,32,128,152,
72,136,124,244,146,0,185,26,248,134,134,193,245,80,207,225,75,167,143,51,177,158,254,251,143,225,239,211,157,79,24,222,156,120,13,73,0,140,200,237,1,62,96,9,0,236,17,92,232,4,71,8,99,64,46,3,83,62,48,71,200,3,139,225,207,95,241,108,215,38,167,241,247,
27,178,5,11,116,31,17,104,212,239,229,17,232,254,122,208,214,111,62,72,98,248,254,138,129,65,68,22,88,39,3,19,193,199,223,148,31,119,203,4,109,79,124,2,86,47,202,250,12,76,160,163,236,131,11,32,107,34,174,0,187,122,183,23,66,54,121,128,23,126,252,135,
231,124,240,197,32,192,190,254,243,3,207,25,24,129,41,225,48,187,196,241,134,61,231,143,161,229,252,111,4,114,255,63,66,227,236,0,1,68,170,247,96,9,0,189,75,136,205,81,223,223,127,255,245,185,227,9,243,225,43,58,86,23,254,3,251,221,207,118,61,5,175,92,
1,221,106,129,2,64,37,193,139,163,192,54,65,43,208,180,151,224,3,158,153,170,150,48,48,154,187,64,170,131,127,127,169,147,19,65,237,11,121,77,6,38,215,56,200,82,171,39,123,32,13,64,240,142,93,22,200,221,59,119,87,128,183,119,49,129,54,119,74,128,174,
99,249,65,94,239,4,182,199,15,216,191,103,248,240,157,129,209,57,132,129,169,114,62,120,103,51,120,65,236,233,90,6,134,27,179,33,85,33,8,195,14,117,2,13,163,3,123,78,175,129,37,38,40,231,255,251,252,151,225,162,145,235,233,202,51,79,15,32,149,184,232,
145,143,173,238,71,46,250,113,38,2,128,0,34,181,10,64,95,45,132,173,49,136,226,184,215,31,63,125,108,59,251,228,192,109,3,171,203,191,63,254,97,120,180,238,62,195,183,251,160,227,214,144,207,180,97,130,96,208,82,232,211,213,192,0,187,14,222,115,207,84,
52,155,129,209,46,0,152,19,191,67,239,209,165,32,17,128,143,126,97,97,96,114,8,101,96,144,82,130,12,70,129,26,94,140,240,11,180,128,57,15,216,254,120,184,22,114,7,143,162,62,3,131,115,48,176,113,248,27,106,47,35,241,145,14,30,211,7,6,193,235,207,224,
21,199,140,81,185,224,59,4,193,187,157,64,165,206,169,50,96,226,219,10,89,31,9,110,237,195,79,244,2,182,79,88,25,190,92,255,200,240,226,240,115,134,223,111,254,50,220,176,112,57,95,181,235,204,222,223,255,254,125,67,11,223,47,72,108,146,26,126,200,0,
32,128,152,27,26,26,24,26,27,27,41,109,218,96,59,139,14,126,206,240,251,143,31,255,92,250,206,244,220,196,64,83,128,251,206,125,209,175,15,190,48,112,8,177,51,176,203,65,23,58,252,249,15,221,51,207,2,217,242,12,42,138,65,219,158,101,44,25,24,245,157,
33,126,187,4,44,253,190,65,215,28,48,147,49,125,252,227,59,120,115,38,232,4,112,208,69,79,12,215,103,66,18,0,11,23,194,233,160,118,0,168,68,248,5,44,9,100,128,165,15,159,36,195,255,163,43,33,215,190,179,67,237,69,142,100,100,12,242,7,168,91,247,249,7,
228,104,58,30,118,6,70,87,96,73,150,213,199,192,228,145,2,217,252,114,115,62,164,216,7,45,133,7,217,11,91,53,13,138,34,208,29,76,92,204,12,159,206,191,103,120,188,225,33,48,147,252,96,184,99,235,124,177,122,255,165,61,79,95,191,253,128,20,249,160,136,
255,140,39,1,160,15,251,226,5,0,1,196,8,222,229,75,90,206,66,191,89,4,148,149,65,201,24,52,139,2,10,77,208,46,14,94,52,12,18,227,210,86,86,20,233,82,102,13,18,127,116,75,142,141,159,149,65,202,77,142,65,200,84,136,129,17,84,37,124,133,186,25,188,29,250,
39,228,18,4,121,63,232,70,9,54,200,222,192,77,83,128,197,230,73,134,255,223,254,66,22,145,128,150,112,17,154,185,131,230,70,70,14,110,6,166,166,13,12,12,6,142,192,198,222,38,72,117,3,178,135,137,13,179,155,8,2,160,37,107,202,177,12,255,79,108,99,96,88,
80,203,240,15,180,53,237,43,212,167,160,222,12,108,131,11,232,206,194,159,144,144,96,20,226,7,230,114,96,3,83,11,216,173,179,14,4,118,41,245,128,161,194,6,185,9,245,234,52,96,130,59,1,41,137,208,78,244,2,87,137,223,126,51,188,62,249,154,225,197,222,39,
12,63,95,255,97,184,100,225,118,166,227,208,165,195,183,159,190,120,131,22,241,32,252,9,74,163,39,128,63,248,70,253,176,1,128,0,34,39,1,160,39,2,22,180,68,192,13,197,232,137,0,36,198,37,193,201,202,159,110,162,98,232,247,233,166,11,168,169,195,37,203,
207,32,237,41,197,192,173,198,143,72,4,96,167,255,133,68,16,159,60,3,131,54,48,17,72,185,64,78,245,126,114,147,225,255,186,126,134,127,123,150,65,210,59,232,100,46,88,137,128,182,249,24,60,226,247,13,180,0,149,15,216,223,6,214,191,54,192,250,247,254,
106,96,203,187,3,98,62,19,27,238,97,15,144,89,234,137,12,12,154,217,224,155,79,25,158,220,98,248,119,12,152,128,78,237,0,111,111,3,151,88,160,102,58,191,48,3,35,104,72,89,199,150,129,17,52,140,11,186,129,20,180,176,228,31,48,190,238,46,103,96,120,186,
11,168,255,57,164,149,207,200,136,122,100,14,19,164,190,255,124,237,3,176,125,244,156,225,203,253,143,12,255,121,184,255,108,100,22,223,63,253,218,171,115,111,63,131,78,156,130,23,247,95,144,34,254,51,82,15,0,91,228,19,125,72,2,64,0,145,155,0,144,19,
1,51,90,34,224,68,42,9,120,144,74,0,24,230,100,102,98,228,140,119,177,85,75,249,112,222,135,237,203,103,46,54,126,78,6,25,79,105,6,65,107,49,160,151,254,32,109,247,102,132,44,33,3,229,26,25,55,6,6,173,44,160,105,202,144,125,117,87,142,48,252,95,210,12,
190,153,147,225,199,111,168,43,88,144,6,123,254,130,175,113,1,69,10,99,102,47,3,163,146,1,176,161,185,143,129,225,68,9,228,88,53,22,78,252,97,244,31,26,142,210,192,238,162,86,46,48,249,202,33,142,192,67,30,37,4,29,47,3,222,247,192,4,209,3,58,38,231,193,
58,200,141,158,224,11,29,217,160,67,186,140,152,51,227,64,125,175,14,190,96,120,182,231,41,195,191,111,127,24,126,72,73,127,154,203,162,176,99,241,190,227,183,254,252,251,135,220,166,250,140,148,0,96,137,1,214,242,39,106,200,23,23,0,8,32,74,19,0,210,
176,30,252,110,58,228,68,192,141,37,17,112,67,229,57,108,100,132,164,235,53,5,189,133,158,223,19,103,230,100,97,148,116,146,102,16,177,22,5,86,141,160,211,58,254,161,22,203,127,191,66,174,164,145,7,230,98,149,72,160,41,178,16,39,60,188,198,240,239,228,
54,112,213,192,240,246,57,36,177,128,150,121,75,171,48,48,58,69,131,79,213,0,135,7,232,138,250,163,192,4,244,227,53,164,203,71,76,24,129,34,20,52,111,193,14,84,47,233,2,89,203,40,164,5,29,169,99,130,204,223,255,2,86,207,159,238,0,35,254,10,164,129,7,
218,19,9,78,96,92,152,11,57,224,189,30,70,134,127,191,255,131,199,70,158,238,125,10,108,250,48,253,127,201,47,254,180,249,230,151,29,199,95,124,124,134,165,159,255,25,173,222,255,138,20,249,191,72,173,247,145,1,64,0,81,146,0,208,27,128,176,146,0,118,
209,52,122,34,64,198,92,176,68,192,193,198,198,217,109,33,235,100,241,253,185,1,227,167,111,172,2,90,66,12,82,30,82,12,236,50,92,224,75,194,33,39,127,192,6,83,254,64,26,105,160,126,179,74,52,176,142,6,38,4,118,96,213,193,200,142,187,227,2,154,230,125,
180,29,216,0,155,13,90,196,6,116,33,129,141,22,88,7,113,64,103,25,124,129,158,134,202,9,57,22,31,20,193,160,42,10,212,96,4,173,217,3,177,65,173,122,112,163,18,203,34,78,200,129,187,12,255,152,254,51,252,120,250,157,225,201,150,39,12,31,111,125,96,248,
203,203,245,253,152,136,198,217,242,93,23,142,0,115,61,242,4,219,87,2,141,190,31,132,22,123,16,3,0,2,136,210,4,128,173,213,15,75,4,200,13,67,110,164,132,192,141,158,8,64,106,155,92,140,44,92,94,92,181,102,251,253,147,131,133,151,141,65,204,74,148,65,
216,76,148,1,116,75,25,234,21,235,208,253,132,160,8,1,221,81,40,102,13,185,68,153,95,13,104,26,244,126,36,80,233,249,11,40,255,234,36,164,107,9,26,231,7,29,170,0,26,111,32,123,5,10,244,40,60,6,232,105,101,224,209,67,38,104,241,206,132,148,219,177,47,
223,254,15,196,127,62,253,2,15,134,189,60,250,146,1,116,208,214,55,62,158,143,203,127,139,28,152,126,254,254,21,44,131,106,95,145,138,123,228,92,255,29,75,127,159,232,70,31,58,0,8,32,106,36,0,108,61,3,102,180,146,0,189,52,128,37,8,46,40,6,39,130,20,93,
25,237,96,129,63,230,34,31,223,72,252,255,242,135,153,75,150,147,65,214,75,150,129,71,131,31,82,45,128,27,118,255,161,87,187,253,135,108,47,3,237,51,0,207,43,179,65,138,106,208,190,195,223,159,33,231,231,130,115,37,59,228,28,61,70,106,222,248,192,136,
54,60,130,69,26,212,38,96,130,206,228,1,123,10,31,206,189,97,120,126,240,57,195,183,199,192,238,40,39,211,223,55,98,178,47,230,223,255,124,120,213,189,119,183,209,166,214,191,33,213,241,95,176,12,246,252,66,154,233,251,71,78,189,143,12,0,2,136,90,9,128,
80,34,64,111,23,112,227,74,4,42,194,124,130,121,90,98,230,106,108,127,228,184,222,188,227,231,101,254,198,45,102,41,194,192,167,42,200,192,12,186,15,79,128,21,88,10,179,64,18,194,31,164,165,139,224,99,212,96,97,194,2,29,87,96,102,160,235,85,31,140,208,
46,34,48,60,255,2,27,117,191,63,253,102,248,243,229,55,195,199,43,111,193,185,254,43,11,207,215,239,130,130,159,174,255,227,124,208,125,225,217,241,167,31,193,173,252,31,88,114,62,182,73,158,159,164,142,243,19,3,0,2,136,154,9,0,87,34,96,129,38,0,118,
44,165,1,50,205,137,84,37,176,73,11,240,242,58,75,112,201,123,11,177,233,42,125,124,169,200,194,250,139,25,116,43,54,175,18,63,131,128,150,0,3,183,34,15,3,51,232,112,10,80,66,0,53,24,255,13,192,82,110,216,9,35,160,238,28,27,100,6,239,215,251,159,12,223,
30,125,101,248,120,237,61,195,151,135,159,25,126,189,251,193,240,135,137,235,239,53,97,217,155,251,95,124,190,121,232,229,151,199,247,223,126,250,136,20,161,223,113,204,236,125,67,171,239,145,183,120,253,163,70,228,131,0,64,0,81,59,1,224,106,19,160,143,
21,112,34,229,124,228,82,0,150,8,96,9,134,85,150,143,139,47,70,83,74,211,130,253,151,134,212,251,231,210,192,46,31,19,43,15,19,3,191,166,16,3,191,190,16,176,51,192,13,57,171,8,182,43,9,52,48,3,154,122,254,135,165,180,166,70,132,195,250,239,32,251,96,
211,219,64,59,65,39,115,126,190,249,137,225,221,133,55,12,223,158,124,1,230,254,127,12,140,124,92,255,158,240,137,61,61,250,254,231,141,25,183,222,94,252,242,243,23,114,17,142,28,249,216,38,118,190,163,141,240,33,79,240,80,37,242,65,0,32,128,104,145,
0,208,123,7,200,35,134,172,72,145,203,129,20,233,232,165,0,188,36,128,98,86,67,113,126,17,43,45,85,73,107,166,143,234,202,159,95,41,50,189,251,200,198,202,207,204,192,41,197,195,192,37,205,13,196,92,12,28,98,156,224,123,115,25,121,88,225,187,102,225,
137,225,223,127,242,154,73,208,214,59,164,44,99,134,38,180,255,12,255,63,255,102,248,254,246,39,3,232,176,172,239,79,190,49,124,125,252,153,225,251,139,47,192,162,255,63,195,47,46,206,31,247,36,212,238,29,127,243,245,222,209,71,111,158,92,120,249,225,
45,3,238,229,116,216,102,82,145,87,245,252,198,50,187,247,159,90,245,26,64,0,209,42,1,224,74,4,176,132,192,134,86,26,112,34,37,0,46,36,113,14,36,181,172,208,18,129,215,144,159,69,60,64,75,65,75,231,227,67,117,230,143,31,217,192,183,166,115,48,50,176,
242,178,51,112,8,115,49,112,43,1,19,133,44,48,65,8,114,48,176,129,206,234,3,109,89,99,66,58,105,3,148,24,254,226,9,63,208,78,103,216,186,5,240,110,102,208,112,242,31,134,95,31,127,131,115,250,151,7,95,128,197,252,23,240,129,204,191,63,127,103,0,117,222,
64,199,18,127,226,230,255,112,142,67,252,198,254,167,159,238,157,127,253,249,213,179,79,224,157,58,232,219,234,144,35,31,121,53,21,114,113,255,19,203,162,142,127,148,180,246,113,1,128,0,162,101,2,96,96,192,188,133,140,25,203,120,1,7,18,230,196,82,10,
112,64,19,0,27,18,102,145,228,227,226,209,224,102,22,50,149,20,144,50,22,96,87,80,248,254,78,154,229,243,59,78,240,249,255,160,140,202,197,6,108,252,179,50,176,2,187,145,108,2,108,12,156,98,28,192,68,194,12,20,7,54,34,121,89,24,88,65,147,47,56,218,135,
191,191,255,1,54,222,254,128,27,112,127,127,252,101,248,249,250,39,48,226,127,1,35,251,39,248,190,4,240,81,185,44,144,218,248,175,176,232,143,155,12,236,15,174,252,102,127,178,231,238,139,135,183,62,255,250,240,249,39,248,62,122,228,101,244,191,144,34,
246,59,3,238,133,156,63,209,90,249,127,177,204,235,83,181,177,3,16,64,180,78,0,184,218,5,200,195,199,232,213,2,114,238,231,68,19,71,78,8,32,125,44,236,204,76,192,38,0,11,135,48,55,39,151,133,146,180,184,62,235,79,41,29,230,111,74,252,31,95,9,129,51,49,
35,11,195,63,208,134,89,208,108,48,23,19,248,58,53,208,197,17,204,176,141,172,88,130,19,116,206,238,255,127,144,9,31,208,117,185,32,215,50,131,174,98,253,243,151,225,255,223,191,12,111,165,52,94,94,123,255,233,201,101,118,137,39,39,110,221,123,245,242,
227,215,175,159,254,252,251,249,243,207,223,95,12,152,231,41,252,64,203,249,63,208,18,193,79,44,221,187,223,72,35,123,255,168,89,228,163,3,128,0,162,87,2,32,84,37,160,151,8,236,72,52,39,22,49,118,164,68,0,211,207,204,194,196,4,76,16,140,44,188,108,44,
108,170,10,242,188,6,2,236,162,226,207,175,11,241,201,40,176,138,139,138,241,49,63,190,197,198,193,240,151,157,71,84,146,141,229,231,55,86,112,93,142,230,119,208,221,104,127,216,57,127,127,122,247,250,199,207,255,204,191,127,73,43,127,123,251,250,245,
247,15,207,30,255,124,35,171,243,254,252,243,119,175,111,61,121,254,9,216,160,251,253,243,31,195,159,63,255,254,193,114,42,182,131,52,126,98,201,249,216,54,111,160,239,226,253,71,171,34,31,29,0,4,16,61,19,0,190,42,1,185,68,64,30,59,64,79,16,28,132,18,
1,3,218,245,232,12,168,187,43,176,94,137,135,163,173,207,128,165,193,133,126,150,50,250,25,10,191,209,114,61,122,100,163,71,58,174,237,219,52,43,242,209,1,64,0,209,123,99,62,242,37,172,200,129,137,126,44,45,44,32,217,144,104,88,0,34,39,0,88,34,96,193,
147,8,152,240,44,90,193,215,217,195,22,241,196,68,254,79,28,137,224,23,150,150,61,174,136,255,207,64,167,209,43,128,0,26,136,147,25,112,229,176,255,72,129,202,140,22,176,172,208,192,99,135,6,38,59,90,41,193,134,148,0,88,176,36,0,92,137,0,215,184,46,250,
81,57,12,12,152,39,168,227,58,67,9,57,1,252,194,81,204,35,183,238,209,235,122,6,6,58,238,77,2,8,32,122,87,1,196,84,11,76,56,218,8,172,104,61,1,54,180,42,128,13,45,1,192,48,35,145,213,1,177,197,62,182,131,52,127,225,40,5,126,227,137,248,127,244,46,238,
177,1,128,0,26,12,9,128,1,75,132,224,75,8,44,88,34,29,57,145,48,227,168,6,112,94,161,142,167,248,255,79,32,1,252,69,139,92,108,24,219,9,93,3,30,241,48,0,16,64,131,41,1,16,91,34,48,35,69,52,11,26,155,25,75,2,32,183,4,96,192,146,0,254,99,73,0,127,145,34,
248,55,26,251,239,96,141,120,24,0,8,160,193,152,0,112,37,4,70,164,72,101,38,128,153,112,244,4,112,229,124,66,13,65,98,74,2,108,248,223,64,215,241,132,0,64,0,177,48,12,94,128,28,72,127,145,122,15,140,80,62,122,233,192,68,160,200,103,194,146,176,136,41,
1,24,176,180,206,255,225,104,20,98,187,156,105,80,70,60,12,0,4,208,96,78,0,248,18,194,63,180,136,101,196,18,233,132,234,124,98,75,0,108,189,21,108,221,194,255,12,216,175,103,27,148,17,15,3,0,1,52,20,18,0,174,238,35,3,150,196,192,128,150,211,241,69,60,
169,9,0,87,15,129,129,1,247,197,140,255,7,123,160,2,4,208,80,74,0,184,18,2,250,200,222,95,34,70,253,24,73,176,3,215,216,5,190,132,57,100,0,64,0,13,197,4,64,76,201,64,40,146,73,77,0,164,202,15,25,0,16,96,0,155,121,235,71,10,157,3,42,0,0,0,0,73,69,78,68,
174,66,96,130,0,0 };

const char* BinaryData::juce_icon_png = (const char*) temp_cf125308;
