/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef HEADERGUARD
#define HEADERGUARD

EDITORHEADERS


//==============================================================================
/**
*/
class EDITORCLASSNAME  : public AudioProcessorEditor
{
public:
    EDITORCLASSNAME (FILTERCLASSNAME* ownerFilter);
    ~EDITORCLASSNAME();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // HEADERGUARD
